### ISSUE TITLE
Names of countries aren't localized

### ISSUE THREAD

**Issue by lagleki** [Tatoeba/tatoeba2#621] opened 2015-03-23 15:59 UTC
1. Open http://dev.tatoeba.org/spa/user/edit_profile while being logged in
2. Names of countries are in English.

What should be instead:
names of countries in Spanish.

Solution:
add necessary strings to Transifex?

**Comment by trang** [comment] 2015-03-23 20:10
Duplicate of #151.

**Closed by trang** 2015-03-23 20:10 UTC
