### ISSUE TITLE
Ratings should be visible also to not logged users

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1606] opened 2018-07-17 07:50 UTC
As suggested by PaulP on the wall:

> Suggestion: The green, yellow and red marks can only be seen by people who logged in. Wouldn't it be good that also occasional users are warned of bad sentences by the red marks?

https://tatoeba.org/ita/wall/show_message/29467#message_29467

**Comment by ckjpn** [comment] 2018-07-17 23:20
This is an "experimental option" that is in the settings.

"Options in this category are not fully functional, may not work for everyone and/or are in a phase of beta testing. They may change or be removed in the future."

Activate the feature to rate sentences and build your collection of sentences.


I think these only show if a member has chosen this setting, which means it won't show if you're not signed in.

**Comment by ckjpn** [comment] 2018-07-18 01:43
Related:

People can only see these ratings if they actually visit each sentence's page.

Perhaps many members do more translating when sentences are shown in lists.

**Comment by agrodet** [comment] 2020-02-12 10:29
I personally think that it is not a good idea. Visitors aren't very likely to know what the review feature is about. However, they are much more likely to believe that what they see is widely used by users of the website. That is not the case, and probably will never be. With the current icon, a very probable side effect is that visitors will think that sentences marked green are "good sentences", hence the ones with no mark aren't. 

For the same reason, I think that #991 is not a good idea (at least in the proposed form). This time, not because of visitor behavior but member behavior. The problem is less in weighing sentences (that can be debatable) than in "reviewed versus unreviewed" sentences. Some may say that if one knows how the review feature works, one will not be influenced. I argue that visual design is more powerful than any other, hence they will be influenced. For example, by translating sentences that have more green checks.  
That is creating an unfair bias towards reviewed sentences. Not only unfair, but probably wrong. As an illustration, the only green checks I sometimes add are to correct sentences of users I proofread. But I proofread these users because they are very likely to have provided wrong sentences. Therefore, looking at my green checks would imply a bias towards sentences of "RandomGuy that probably isn't native or very good at grammar" instead of sentences of sacredceltic, the exact opposite of what I would advise. 

Now, I understand that for people using the review feature, it might be frustrating to not see their effort widely recognized and used. I also admit that this feature can be very useful in several situations. For example, sharing the load of proofreading a user. If I see that somebody else I trust proofread these sentences, I may feel like skipping them. At it was mentioned numerous times, the issue with this feature is the "like / unlike" behavior that goes beyond what it is supposed to be (okay, not okay). 

Personally, as I argued before, I think there would be less problems if everybody assumed the green mark on every unmarked sentence. Every sentence is supposed correct until proved otherwise (the red / orange marks) and there's no competition / weighing of any kind.

**Comment by jiru** [comment] 2020-02-29 11:29
The feature is still experimental, so it’s not showed not only to guests but also members who didn’t activate it. It will become visible for guests only when the feature gets out of experimental state.

**Closed by jiru** 2020-02-29 11:29 UTC
Labels: enhancement
