### ISSUE TITLE
Duplicated strings are allowed while original is still being sent

### ISSUE THREAD

**Issue by SafaAlfulaij** [Tatoeba/tatoeba2#1626] opened 2018-07-30 16:49 UTC
Sometimes while translating my internet lags, and the translation submitting loader keeps spinning, so I just go and press the translation icon and then "Add translation" again, assuming it will be faster (sorry server).
It seems that the server can't check duplication here and just allow it.
Examples (the Arabic translations):
https://tatoeba.org/ara/sentences/show/6983814
https://tatoeba.org/ara/sentences/show/5869290

**Comment by jiru** [comment] 2018-08-29 21:43
I’m unable to reproduce the problem locally, so it’s hard to solve.

It’s probable due to a race condition with two sessions checking duplicate at the very same time. If it’s true, then one way to solve that problem is to use a locking mechanism. It looks like InnoDB has some [cool locking facilities we could use](https://dba.stackexchange.com/questions/116193/lock-mysql-table-to-prevent-select-and-insert-at-the-same-time).

**Comment by agrodet** [comment] 2020-01-25 14:59
Even if this problem happens, Horus will take care of the sentences later, right? I don't know how the duplicate check is done when adding a sentence, but since it's an irregular situation that doesn't lead to a unexpected situation, probably that's not a big deal. I faced the "forever spinning" problem many times in the past, but I can't remember if I have faced it recently... Except during exceptional period like the recent attack, of course.

**Comment by jiru** [comment] 2020-02-06 09:41
I agree. I also suspect that the problem was caused by #1837.

@SafaAlfulaij I’m going to closing this issue for now, but feel free to reopen it if you experience this issue again.

**Closed** 2020-02-06 09:42 UTC
Labels: bug
