### ISSUE TITLE
Searching for items with a slash gives strange results.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1062] opened 2016-03-11 16:14 UTC
## Unquoted search including /

If the search isn't quoted, you get an error message.

24/7
https://tatoeba.org/eng/sentences/search?query=24%2F7
![screen shot 2016-03-12 at 01 17 12](https://cloud.githubusercontent.com/assets/7934273/13708112/3c7eb30e-e7f0-11e5-8139-f78bb58941ee.png)

## Quoted searches including /

https://tatoeba.org/eng/sentences/search?query=%22he%2Fshe%22

![screen shot 2016-03-12 at 01 12 51](https://cloud.githubusercontent.com/assets/7934273/13708014/bd209a82-e7ef-11e5-9fa8-c95c7bc4962f.png)

https://tatoeba.org/eng/sentences/search?query="km%2Fh"

![screen shot 2016-03-12 at 01 15 41](https://cloud.githubusercontent.com/assets/7934273/13708065/02663f20-e7f0-11e5-8bac-f33575be0326.png)

**Comment by trang** [comment] 2016-03-11 16:20
Duplicate of  #1050.

**Closed by trang** 2016-03-11 16:20 UTC
Labels: bug
