### ISSUE TITLE
Allow users to choose sort order of tagged items.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#724] opened 2015-07-20 02:01 UTC
Here is a possible enhancement that might help people translate tagged sentences.

Option 1 - No Change -  Some members will like the current method, since they can start at the beginning and systematically translate all sentences in a given language with a certain tag.

For example, sentences tagged OK in English.

http://tatoeba.org/eng/tags/show_sentences_with_tag/7/eng/page:1

Option 2 - Other members may prefer to translate in the reverse order, starting with the most-recently tagged items.

The following URL isn't exactly what I mean, but it's close.  

http://tatoeba.org/eng/tags/show_sentences_with_tag/7/eng/page:999999
This URL should jump you to the last page of English sentences tagged OK.

Note that the "advanced search" doesn't get the same results, even though there is a "sort by last created" and "last modified" option.  This, apparently, is based on the sentence, not on the tagging.

If option 2 were the only choice, members couldn't easily bookmark a page and resume where they left off, since newly-tagged sentences would push items to higher-numbered pages.

**Comment by trang** [comment] 2016-06-07 09:39
Duplicate of #960.

**Closed by trang** 2016-06-07 09:39 UTC
Labels: enhancement
