### ISSUE TITLE
Pagination for "browse by language" is wrong - 

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#831] opened 2015-10-14 16:34 UTC
https://tatoeba.org/eng/sentences/show_all_in/pam/eng/indifferent/indifferent/page:29

Page 30 and 31 are blank.

Also, I have my settings to display 20 sentences per page, but I'm only getting 10 per page.
Perhaps this is a new bug that has crept in.  I didn't notice it until today.
Maybe this is related.

![screen shot 2015-10-15 at 01 29 18](https://cloud.githubusercontent.com/assets/7934273/10490505/68522b5c-72dc-11e5-94cf-7a4943ef5344.png)

**Comment by trang** [comment] 2016-05-01 17:16
@ckjpn, I wasn't able to reproduce this problem and neither was @RyckRichards. I'm marking this as rejected for now. If you cannot reproduce it either, please close this issue.

**Comment by trang** [comment] 2016-05-25 00:30
Closing this. Feel free to re-open if you can reproduce it.

**Closed by trang** 2016-05-25 00:30 UTC
Labels: bug, status:rejected
