### ISSUE TITLE
On the "Languages of Members" page, the fluency symbols are out of place

### ISSUE THREAD

**Issue by sabretou** [Tatoeba/tatoeba2#2289] opened 2020-04-19 12:31 UTC
I'm using Windows 10 64-bit desktop to use Tatoeba. On my computer, the fluency bars on the "Languages of Members" page are out of place. 

This bug can be replicated across:

- Firefox 64-bit 76.0b5
- Chrome 64-bit 81.0.4044.113
- Edge (Unknown version, thanks Microsoft)

The bug is present on both the main website and the development website. It also present regardless of UI language setting (I have tested English and Marathi).

This bug is **not** present when I use Tatoeba on Firefox for Android.

Screenshots:

Firefox (Main website):
![image](https://user-images.githubusercontent.com/7028559/79687772-3cb5a100-8267-11ea-9097-bebe40fe07f6.png)

Chrome (Dev website):
![image](https://user-images.githubusercontent.com/7028559/79687794-61117d80-8267-11ea-8561-dbd1d4d4c336.png)

**Comment by jiru** [comment] 2020-04-20 06:22
Just to clarify, are you talking about the blue bars that overlap a little bit over the bottom of their frames? On my machine running Linux, I can reproduce the problem with Chromium but not Firefox...

**Comment by sabretou** [comment] 2020-04-20 12:53
@jiru Yes, I am referring to the blue bars that are placed slightly lower than they should be, overlapping the frames.

**Comment by AndiPersti** [comment] 2020-04-20 20:21
The misalignment is dependent on the browser font size. I can reproduce it on Linux with both Firefox and Chromium if I set the font size to a value bigger than 15px (the height of the containing `div` is set to 15px).

I've pushed a fix which works for me with Firefox 75 and Chromium 81 (both on Linux) and the stock Android Browser 6.0.1, Firefox Preview 4.2.1 and IceCatMobile 68.4.2 (all on an Android tablet). But I suggest to also test it on dev.

**Comment by jiru** [comment] 2020-04-21 04:39
I pushed Andreas’ fix on [dev.tatoeba.org](https://dev.tatoeba.org/eng/stats/users_languages) if anybody wants to test.

**Comment by sabretou** [comment] 2020-04-21 05:56
I checked dev, and it looks perfect to me now!

**Comment by jiru** [comment] 2020-04-23 08:15
Thanks for confirming, @sabretou!

**Closed** 2020-04-26 16:30 UTC
Labels: bug
