### ISSUE TITLE
Feature Request: Add the Sentence's ID into the "alt" of the image, so when copying sentences from a page, we get the sentences' IDs, too.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1699] opened 2018-10-13 01:07 UTC
## The Request
 
I wonder if the sentence ID number could be put in the "alt" of the flag image.

If so, then when someone copied a sentence or a group of sentences on a page instead of the following.

eng
What in the world was I thinking?

... we could get the following.

eng #7285528
What in the world was I thinking?

## The Reason

When copying sentences to paste into comments, it would be useful to have the links.

It would likely be useful for other purposes, too.

## The HTML
Here is how the HTML would look.
```
<img src="/img/flags/eng.png?1538936187" id="flag_7285528" class="languageFlag editableFlag" width="30" height="20" data-sentence-id="7285528" title="English" alt="eng #7285528"/>
```
This is was was on the page.
```
<img src="/img/flags/eng.png?1538936187" id="flag_7285528" class="languageFlag editableFlag" width="30" height="20" data-sentence-id="7285528" title="English" alt="eng"/></div><div class="content column"><div data-sentence-id="7285528" class="sentenceContent"><div lang="en" dir="ltr" ng-non-bindable="" class="text correctnessZero editableSentence" id="eng_7285528" data-submit="OK" data-cancel="Cancel">What the in the world was I thinking?</div></div></div><div class="audio column"><a href="http://en.wiki.tatoeba.org/articles/show/contribute-audio" title="No audio for this sentence. Click to learn how to contribute." class="audioButton audioUnavailable" onclick="window.open(this.href); return false;"></a>
```

## Another Possibility

Maybe an "alt" with the sentence's number could be added into the images just to the left of the flag icons.  The green # and the blue and gray arrow icons.  This might accomplish the same thing.

**Comment by jiru** [comment] 2019-03-15 05:51
The `alt` attribute is meant to be used to describe the image instead. Putting the sentence number there will mess up with any implementation that follows this standard, such as screen readers.

Your use-case sound like a kind of export function to me. Copy-pasting isn’t really meant to be used on formatted text in the first place.

**Comment by trang** [comment] 2019-12-13 19:48
Closing because duplicate of #1261.

**Closed by trang** 2019-12-13 19:48 UTC
Labels: enhancement, unclear
