### ISSUE TITLE
Valencian

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1048] opened 2016-03-08 02:32 UTC
- Language name: Valencian
- Language info: https://en.wikipedia.org/wiki/Valencian_language
- ISO 639-3 code: **any yet**
- Public List: https://tatoeba.org/eng/sentences_lists/show/5812
- Icon: https://en.wikipedia.org/wiki/Valencian_Community#/media/File:Flag_of_the_Valencian_Community_%282x3%29.svg
- Requested by: [isnamar](https://tatoeba.org/eng/user/profile/isnamar) and [cueyayotl](https://tatoeba.org/eng/user/profile/cueyayotl)

**Comment by RyckRichards** [comment] 2016-03-08 02:33
By [cueyayotl](https://tatoeba.org/eng/user/profile/cueyayotl) on the [Wall](https://tatoeba.org/eng/wall/show_message/25696#message_25696)

> I wonder if we couldn't add Valencian as a separate language, distinct from Catalan, due to political reasons? Valencian speakers are usually very insistent that their language is distinct from Catalan, and I wonder how many potential members we may have lost due to our current classification scheme, an issue brought to my attention by our new Valencian user (isnamar).

The main issue is that they share the same ISO 639-3 code: CAT.

> They are probably as far apart as Galician and Portuguese (which HAVE two different ISO 639-3 codes) and probably more dissimilar, than say, varieties of English.

You are right, though. We would get plenty of duplicates and near duplicates (they use different spelling conventions). But, in the present state, we would definitely be repelling potential Valencian-speaking users who are not comfortable with the "Catalan" classification of their language. We would be throwing out a big chunk of our corpus... a shame, as Valencian is quickly being spoken less and less.

I wonder if there is something more clever that we could do... maybe have both languages (and flags)... but catalog all sentences under the code "CAT" as usual. There MUST be something...

**Comment by jiru** [comment] 2016-03-08 03:24
We just can’t add languages without an ISO code.Also, as CK said on the Wall, what about all the sentences that can be considered valid in both Catalan and Valencian?

**Comment by RyckRichards** [comment] 2016-03-08 14:50
By [cueyayotl](https://tatoeba.org/eng/user/profile/cueyayotl) via private message:
(Note: he authorized me to do so)


> The language is not near extinction now, but it may very well be one of the languages lost this century.

> I believe the Summer Institute of Linguistics (the ISO 639-3 guys) has firmly rejected giving Valencian its own language code, on the grounds that it is too similar to Central Catalan. I believe it is another one of their big mistakes, in which they do not draw political boundaries between language.

> Whatever we do, we should prepare just in case the SIL decides to finally allow Valencian its own language code, then we can simply move all of the sentences in Valencian into THAT code after the following Tateoba update. I know that that is possible because we have already done that when one of the Norwegian languages had been listed under the ISO 639-3 code for Old Norse for several years.

**Comment by RyckRichards** [comment] 2016-03-08 14:51
According to him, all [isnamar](https://tatoeba.org/eng/user/profile/isnamar)'s sentences are in Valencian.

**Comment by cueyayotl** [comment] 2016-03-24 02:00
I think this issue has been closed, but just to summarize, if we can create a better tagging system and better language icon, separating Catalan and Valencian would be, in my opinion, entirely unnecessary. As user alexmarcelo confirmed on the Wall, potential Valencian users are definitely deterred from joining Tatoeba by seeing a Catalan flag representing their language. Just like we've done with Portuguese, we may have to change that language icon.

**Comment by trang** [comment] 2016-03-24 10:24
@cueyayotl this issue is still open. You can see this if you scroll up, below the title, there's the status "Open" in a green background.

This issue will be closed when we have a new icon for Catalan.

In the Wall thread you also mentioned [modifying the name](https://tatoeba.org/eng/wall/show_message/25771#message_25771) from "Catalan" to "Catalan/Valencian". Modifying the name is also a possibility but for the time being, I would prefer to follow [gillux's idea](https://tatoeba.org/eng/wall/show_message/25776#message_25776) to have a page that defines languages more clearly, where we would explain that the name "Catalan" encapsulates "Valencian".

**Comment by RyckRichards** [comment] 2016-03-24 14:15
I'll also PM members who have posted sentences in Catalan and ask their opinion as far they would have their languages and/or flag changed. Do you have any flags in mind, @cueyayotl ?

**Comment by cueyayotl** [comment] 2016-03-29 06:57
Thank you for explaining, TRANG. I don't know if merely explaining that "Catalan" encapsulates "Valencian" would work, but I will leave the decision to you; we trust that you will do the right thing.

As for a new language icon, I propose simply doing a split flag (in the same way as we did with Portuguese). People were generally opposed to having the Catalan version of the flag with the star, so I just kept the "official" Catalan flag on the left side, and added the Valencian flag on the right.

Here is what it looks like:
http://imgur.com/1wDNqug

Let me know if there are other suggestions.

**Comment by sabretou** [comment] 2019-03-13 03:46
@trang As we have an improved language dropdown now, can we change the language name to "Catalan (Valencian)" and use the icon proposed by cueyayotl? We have previously used a similar solution for Odia (Oriya).

If there are reasonable objections to the icon later, we can use a neutral icon.

**Comment by trang** [comment] 2019-03-13 19:51
Using `Catalan (Valencian)` would imply that Valencian is an alternate name for Catalan, or that Valencian is a dialect of Catalan. 

It could cause confusion to people who are contributing in Catalan: if Valencian is a dialect of Catalan, then non-Valencian speakers might hesitate to add sentences in that category because they might think it's specifically for Valencian

If Valencian is a different language and should be treated as such (which seems to be what is being requested here), then Valencian people might feel offended to see their language being merged with Catalan.

I think here we're in a typical situation where we have users who do not agree with the ISO categorization. But since we have not officially made the decision to step away from ISO 639-3, we would have to reject the request or convince the SIL to add Valencian as an individual language.

**Comment by jiru** [comment] 2019-07-26 09:36
Note that in 2006, a [request to split the ISO code *cat* into two separate codes for Catalan and Valencian](https://iso639-3.sil.org/request/2006-129) has been rejected by the SIL. They gave [detailed reasons](https://iso639-3.sil.org/sites/iso639-3/files/change_requests/2006/CR_Comments_2006-129.pdf) about the refusal.

**Comment by trang** [comment] 2019-07-26 20:29
@sabretou Do you agree to close this issue? Or would you like some time to research more about it?

**Comment by sabretou** [comment] 2019-07-27 09:58
@trang Yes, I've looked into it and I agree at closing the issue.

**Closed** 2019-07-27 21:00 UTC
Labels: lang-request

**Comment by RyckRichards** [comment] 2022-01-12 23:00
This language has an ISO 639-3 code - https://en.wikipedia.org/wiki/Valencian_language


ISO 639-3 | cat

**Comment by sabretou** [comment] 2022-01-13 07:32
@RyckRichards It shares the ISO code with Catalan, which we have already added on Tatoeba. The best we can do is to convince Valencian speakers to use this language code on Tatoeba.

As a modification of my previous suggestion, perhaps we can rename Catalan to "Catalan & Valencian" or "Catalan / Valencian" to accommodate both languages? This will keep both languages on an even footing.

**Comment by LBeaudoux** [comment] 2022-01-13 14:59
@sabretou  Note that the official [ ISO 639-3 language name](https://iso639-3.sil.org/code_tables/639/data?title=cat&field_iso639_cd_st_mmbrshp_639_1_tid=All&name_3=&field_iso639_element_scope_tid=All&field_iso639_language_type_tid=All&items_per_page=200) for `cat`  is `Catalan, Valencian`.

Also, when a sentence matches only one of the two variants, perhaps we could encourage contributors to add `català` or `valencia` tags.
