### ISSUE TITLE
Enhancement for search strings

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#3112] opened 2024-03-31 09:43 UTC
as reported by DostKaplan on the wall:

> I think a great future enhancement would be "Search for < string1 > from < fromLanguage > to < toLanguage > where results contain < string2 >". For example,
> 
> Search string: "wonder if" {acaba}
> From: English To: Turkish
> 
> Results: Sentences in Turkish containing "acaba" where the corresponding English sentence contains "wonder if".
> 
> 🇬🇧 I wonder if I should trust Tom.
> 🇹🇷 Acaba Tom'a güvensem mi?

https://tatoeba.org/it/wall/show_message/40588#!#message_40588

**Comment by jiru** [comment] 2024-04-23 06:41
Closing as duplicate of #1576.

**Closed by jiru** 2024-04-23 06:41 UTC
Labels: enhancement
