### ISSUE TITLE
Reconsider whether to hide translations after a sentence is linked

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#798] opened 2015-10-02 02:50 UTC
Sometimes, a sentence has multiple indirect translations that I want to make into direct translations. The problem is that after linking, the window snaps closed again and the full list of translations is hidden. Thus, I often have to reopen the full list of translations. For example, this screenshot shows how the window has "snapped shut" after I linked the sentence "He said nothing." to the Hebrew: 
![hidden](https://cloud.githubusercontent.com/assets/1213027/10238445/dbea9148-688d-11e5-9de8-e0359ff5d0a5.png)

But this screenshot shows that there's still a sentence ("He didn't say anything.") that I want to link:
![displayed](https://cloud.githubusercontent.com/assets/1213027/10238466/229c1cba-688e-11e5-88b5-ed51df063b61.png)

I realize that this "snapping shut" behavior may be desired by some people, at least in some situations, because they don't want to link multiple sentences and don't want the list to take up so much space. But I personally would prefer for a list to stay open once it has been opened unless I explicitly click on the link to close it. Perhaps this behavior could be controlled by a personal option (separate from the one that controls whether translations are hidden at all -- "Display a link to expand/collapse translations when there are too many translations.") I'll ask on the Wall to see what people think.

**Comment by jiru** [comment] 2019-03-04 18:52
Duplicate of #628.

**Closed by jiru** 2019-03-04 18:52 UTC
Labels: enhancement
