### ISSUE TITLE
For the "add new sentences" page, make it so it searches for an existing sentence first, before adding the sentence.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#781] opened 2015-09-25 12:37 UTC
On this page, https://tatoeba.org/eng/sentences/add, search to see if there is an exact match before adding.

For me, adding a new sentence is a 2-step process.  I would assume other members do the same.

1. Search to see if what I want to contribute is already in the database.
2. If it's not there, I then add it.

If you made this a one-step process, it would save those members who do the same some time.
If would also reduce the number of newly-contributed duplicate sentences by those who don't take the time to search first.

https://tatoeba.org/eng/sentences/add
![screen shot 2015-09-25 at 21 29 27](https://cloud.githubusercontent.com/assets/7934273/10100497/2c561bea-63cd-11e5-88f2-3186915dda27.png)

**Comment by billoliver** [comment] 2016-03-15 23:02
This issue should be one of our highest priority because some new users will always add duplicated sentences. When they see that they are being deleted they will probably not add new ones. Everyone loses, and we do need them, right?

**Comment by trang** [comment] 2016-03-17 08:38
Duplicate of #577.

**Closed by trang** 2016-03-17 08:38 UTC
Labels: enhancement
