### ISSUE TITLE
When merging duplicates, if one of the duplicates is "unapproved" (red), delete it and keep the other one.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#904] opened 2015-11-04 22:21 UTC
When merging duplicates, if one of the duplicates is "unapproved" (red), delete it and keep the other one.

This was mentioned in a message to tatoeba-community-admins@googlegroups.com on Jun 7, 2015.

This may cause problems in case of copyright infringements, but in most cases, this would be the better choice, since the remaining sentences would likely be good and usable.  Copyright infringements are usually tagged, so it might not be a major problem.

**Comment by loolmeh** [comment] 2016-01-31 17:24
@trang 's mind on this hasn't changed, otherwise this is trivial to patch up. closing for now.

**Closed by loolmeh** 2016-01-31 17:24 UTC

**Comment by trang** [comment] 2016-01-31 17:53
For the record, this is the thread in the Google group: [Errors with Duplicate-Merging Script](https://groups.google.com/forum/#!searchin/tatoebaproject/unapproved/tatoebaproject/iXBIPbaNpc0/yjnrUZAhATQJ)

To clarify my point of view, I don't think the problem comes from the deduplication script. The problem is that sentences that are good and usable end up being marked as "unapproved" because of possible copyright infringement.

If this is an inconvenience rather than a convenience, then we should simply stop marking possible copyright infringements as unapproved, and wait until we implement a better solution.

**Comment by ckjpn** [comment] 2016-02-01 01:39
we should simply stop marking possible copyright infringements as unapproved, and wait until we implement a better solution.

Possibly, just add a 3rd option to "unapproved", maybe a -2.
Then turn any sentence marked less than 0 as RED, and untranslatable.

If that was the case, then my guess is that it wouldn't be too difficult to get the duplicate-merging script to as like we want it to act.

Perhaps this issue should be reopened.
