### ISSUE TITLE
Horus leaves multiple comments

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1483] opened 2017-07-26 08:20 UTC
As reported by brauchinet on the wall:

> Horus is behaving strange lately. He leaves messages on merged sentences more than once, e.g. #6166995 or https://tatoeba.org/eng/sentenc...omment-974976. Maybe his view on the database isn't synchronised quick enough.

https://tatoeba.org/ita/wall/show_message/28315#message_28315

**Comment by jiru** [comment] 2019-03-12 12:14
Closing as duplicate of #1722. Feel free to reopen or to open a new issue if the problem occurs again.

**Closed** 2019-03-15 03:13 UTC
Labels: regression
