### ISSUE TITLE
/sentences_lists/show/6685/eng & sentences_lists/show/6685/und - These show the same thing if the user's settings for languages is set.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1918] opened 2019-07-13 00:01 UTC
## Unexpected Results

These both show the same results, if a user has set preferred languages to see.

https://tatoeba.org/eng/sentences_lists/show/6685/und (should show all translations)
https://tatoeba.org/eng/sentences_lists/show/6685/eng (should show only English translations)

## Perhaps no change is needed.

Perhaps there is something that causes this that may cause other problems, so I thought you might like to know.

## The Results
(Same for both of the above URLs)
<img width="769" alt="Screen Shot 2019-07-13 at 8 52 28" src="https://user-images.githubusercontent.com/7934273/61163904-41b52980-a54c-11e9-9a31-e70a9e71430f.png">

## My current settings
<img width="328" alt="Screen Shot 2019-07-13 at 8 54 54" src="https://user-images.githubusercontent.com/7934273/61163907-47ab0a80-a54c-11e9-9736-a69c91e72849.png">

These are languages that had identified native speakers on the website and languages that had at least 500 sentences. (on 2019-07-11)

**Comment by ckjpn** [comment] 2019-07-13 09:52
This is related..
"Show Translations in:" NONE

https://tatoeba.org/eng/sentences/search?query=&from=eng&to=none&orphans=no&unapproved=no&user=&tags=&list=907&has_audio=no&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=created
Looking for recent English sentences on List 907 that don't yet have audio.

<img width="1122" alt="Screen Shot 2019-07-13 at 18 48 23" src="https://user-images.githubusercontent.com/7934273/61170070-20c9f400-a59f-11e9-818a-cf63e958870f.png">

**Comment by trang** [comment] 2019-07-14 12:16
Duplicate of #1918.

**Closed by trang** 2019-07-14 12:16 UTC

**Comment by AndiPersti** [comment] 2019-07-14 15:59
> Duplicate of #1918.

You probably mean duplicate of #1860.

**Comment by trang** [comment] 2019-07-17 09:58
@AndiPersti Indeed, thank you :)
