### ISSUE TITLE
Diacritics are not displayed correctly.

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#863] opened 2015-10-25 00:20 UTC
[By wells](https://tatoeba.org/eng/wall/show_message/24413#message_24413)

> I'm having a minor problem with diacritics getting cut off in the sentence view. Here we have the word 'Ääniala' but it renders as 'Aäniala':
> 
> https://i.imgur.com/AQyDthv.png
> 
> This only applies to sentences I own, so I think the buttons bar is at fault. This is on Mozilla/*nix.
> 
> Here's a second related bug I experience:
> 
> http://i.imgur.com/6MVVHcq.png
> 
> When submitting a new sentence, the 'diacritics' get cut off in the same way. The newly-submitted sentence #4630768 gets chopped but the pre-existing sentence #4629634 displays correctly.
> 
> If I reload the page, both display correctly.
> 
> I need to double-check these sentences for typos whenever this rendering bug shows up.
> 
> And here's a CSS solution that works for me -- fixes both problems and one more:

`div.editableSentence, .addTranslationsTextInput { padding-top: 4px; }`

> (The text input was tight as well, so I added a padding there.)
> 
> I know languages such as Vietnamese use more complex diacritics that take more vertical space. If someone would produce a sentence for me to test with such a language, I'd be happy to test it.
> 
> Edit: It seems the input textboxes are all a bit tight vertically. The Å in Åke gets cut off in the topmost search bar, and in the 'Advanced search' form. This CSS rule fixes it:
> 
> input[type="text"] { padding-top: 5px !important; }
> 
> (It's an 'override' rule. Not something to check into the code.)

**Comment by RyckRichards** [comment] 2016-03-22 23:30
[wells](https://tatoeba.org/eng/user/profile/wells) can still reproduce this bug - https://tatoeba.org/eng/wall/show_message/26027#message_26027

**Comment by halfdan** [comment] 2016-12-29 13:14
I believe this was fixed with #1245 - I can't reproduce this anymore.

**Closed** 2017-01-08 17:34 UTC
Labels: bug
