### ISSUE TITLE
Need a more efficient way to deal with red sentences that are actually fine

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1847] opened 2019-03-28 23:58 UTC
Reported by [Thanuir on the Wall](https://tatoeba.org/eng/wall/show_message/31542#message_31542):

> What to do with red sentences?
>
> There are some sentences which are, as far as I know, completely valid, but they are in red and can not be translated. (E.g. https://tatoeba.org/fin/sentences/show/3313641 , https://tatoeba.org/fin/sentences/show/415526 )

My response:

> Currently, the only solution is to contact an admin so they "re-approve" those sentences.

Some possibilities:
- Automatically remove the red mark if an orphan sentences is adopted by an advanced contributor.
- Allow corpus maintainers to mark/unmark a sentence as red.

**Comment by jiru** [comment] 2019-07-26 11:02
Closing as duplicate of #1659.

**Closed by jiru** 2019-07-26 11:02 UTC
Labels: enhancement
