### ISSUE TITLE
The duplicate-merging script (Horus) needs to be restarted

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1506] opened 2017-09-13 04:50 UTC
https://tatoeba.org/eng/sentence_comments/of_user/Horus
Apparently, this has not been doing its job since 2017-07-28.

**Comment by Guybrush88** [comment] 2017-09-13 07:26
this is a duplicate of #1494

**Closed** 2017-09-17 16:56 UTC
