### ISSUE TITLE
Change the title from "All Sentences in English" to "All Sentences in English with Audio" when "Only sentences with auido: yes" is chosen. 

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1035] opened 2016-03-02 14:25 UTC
Change the title from "All Sentences in English" to "All Sentences in English with Audio" when "Only sentences with auido: yes" is chosen. 

The reason this should be changed is that "All sentences in English" only is not true in this case.

Here is an example link: https://tatoeba.org/eng/sentences/show_all_in/eng/und/none/only-with-audio

![screen shot 2016-03-02 at 23 20 08](https://cloud.githubusercontent.com/assets/7934273/13463083/f1fb28ae-e0cd-11e5-9027-51a5542bb03f.png)

**Comment by trang** [comment] 2016-05-05 20:37
Duplicate of #986.

**Closed by trang** 2016-05-05 20:37 UTC
