### ISSUE TITLE
Tag 4072 has lost its name.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1835] opened 2019-03-23 01:33 UTC
https://tatoeba.org/eng/tags/show_sentences_with_tag/4072

4072	881781	Ricardo14	2014-06-28 00:40:12
4072	2740608	Ricardo14	2014-07-16 15:49:33
4072	1567883	Ricardo14	2014-07-17 02:18:44
4072	1266332	vvv123	2014-11-16 14:05:25
4072	275070	vvv123	2014-11-16 14:05:39
4072	2050923	vvv123	2014-11-16 14:14:20
4072	930436	Ricardo14	2015-09-07 03:21:04
4072	3023562	Ricardo14	2015-09-07 03:25:21
4072	3127613	Ricardo14	2015-09-07 03:47:20
4072	2544065	Ricardo14	2015-09-08 08:23:11
4072	3390601	Ricardo14	2015-09-08 08:25:04
4072	1723794	Ricardo14	2015-09-17 17:59:11
4072	306587	Ricardo14	2015-09-17 18:11:36
4072	2545942	Ricardo14	2015-09-17 20:03:35
4072	2545961	Ricardo14	2015-09-18 01:56:31
4072	3442185	Ricardo14	2015-09-24 21:39:55
4072	2006571	CK	2015-10-08 23:35:15

**Comment by ckjpn** [comment] 2019-03-23 01:43
Perhaps these are other problems.
Lines from tag_metadata.csv

5368	3006367	GrizaLeono	2014-01-25 16:02:33
2584	57577	mookeee	2011-10-09 00:05:04
2582	7775	mookeee	2011-10-08 22:33:52
4072	4072	CK	2015-10-09 07:14:22
9077	1904	Hybrid	2017-10-25 01:07:38
8146	1897	Hybrid	2016-12-13 03:36:37
1798	1890	Scott	2011-01-27 18:49:08
1651	1862	Swift	2010-12-15 20:19:40
9079	1859	Hybrid	2017-10-25 01:13:41
3624	1849	Scott	2012-08-29 19:32:31
3631	1848	Scott	2012-08-29 21:27:53
9081	1843	Hybrid	2017-10-25 01:15:19
9073	1816	Hybrid	2017-10-25 01:00:59
9075	1790	Hybrid	2017-10-25 01:04:17
915	1762	Pharamp	2010-08-30 22:53:52
2581	575	mookeee	2011-10-08 21:04:53

**Comment by ckjpn** [comment] 2019-03-23 01:48
The oldest tag_metadata.csv I have on the hard disk of the computer I'm using now, November 11, 2017, had the same problem.

**Comment by jiru** [comment] 2019-03-27 09:14
This is the only tag which name equals its id. Its internal name is "present_continuous", which suggests the name has changed somehow.

**Comment by ckjpn** [comment] 2019-03-28 00:58
Perhaps you could just assign all 4702 to 6837 which is the "present continuous" tag without an underscore

6837	present continuous	CK	2015-10-10 04:08:46

**Comment by AndiPersti** [comment] 2020-12-13 13:11
I've removed this tag (4072) from all the sentences that still were tagged with it and added the tag `present continuous` to all those sentences that were missing it.

Since as far as I can tell this is the only tag where this issue ever happened and we don't really have a possibility to find out why it happened or whether it is even caused by a bug in the code, I'm closing this.

**Closed by AndiPersti** 2020-12-13 13:11 UTC
Labels: bug
