### ISSUE TITLE
Wrong results when searching by a tag

### ISSUE THREAD

**Issue by denikoTatoeba** [Tatoeba/tatoeba2#1978] opened 2019-10-07 16:45 UTC
I'm searching by @change tag in Ukrainian:

https://tatoeba.org/eng/sentences/search?query=&from=ukr&to=und&orphans=&unapproved=no&user=&tags=%40change&list=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=relevance

The first match is not actually tagged with @change

https://tatoeba.org/eng/sentences/show/496747

I suspect the root of the problem is the following.

I wrote about a problem with this sentence:

https://tatoeba.org/eng/sentences/show/1674966

And tagged it with @change 

The author corrected it, and, as a result, 1674966 merged with 496747. The @change tag was never removed from 1674966 and it might be somehow inherited by 496747, although the sentence is not showing this tag.

**Comment by jiru** [comment] 2020-02-03 11:03
I cannot reproduce this. The link you provide does not show the problem any more. Besides, when I reproduce the merge scenario that you describes, the `@change` tag gets moved to the merged sentence correctly.

It might have been caused by #1944.

Closing this as lack of information. Feel free to reopen if you see this bug again.

**Closed by jiru** 2020-02-03 11:03 UTC
Labels: bug
