### ISSUE TITLE
Select list for a sentence instantly rather than requiring OK button

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#50] opened 2014-02-17 19:55 UTC
Select list for a sentence instantly rather than requiring OK button. Perhaps this could be controlled by a preference setting.FeuDRenais, Wall

---

Original ticket: https://www.assembla.com/spaces/tatoeba2/tickets/390

**Comment by rowbottomn** [comment] 2019-05-11 14:36
This would be a good feature, as making larger lists for machine learning models is tedious.  Unless I am missing something.

**Comment by jiru** [comment] 2019-05-13 04:44
@rowbottomn I labelled this issues as "unclear" because I’m unsure what removing the OK button is good for. Can you elaborate on what you’re trying to do? How is it related to making larger lists for machine learning models?

**Comment by trang** [comment] 2019-08-03 13:59
Closing this. We have no solid ground to decide whether it's better or worse to have the OK button.

I suspect that the real problem is that adding several sentences to a list is tedious, and the user wanted to save some time by not having to click OK every time.

On the Wall, in reply to this feature request, I mentioned:

> I guess the only drawback is that if you click on a wrong list, then it's not easy to cancel.

And another member confirmed that she had a difference preference:

> I personally prefer the current option of having to click on "ok" precisely because of that...

**Closed by trang** 2019-08-03 13:59 UTC
Labels: enhancement, unclear
