### ISSUE TITLE
in list view translate button isn't shown

### ISSUE THREAD

**Issue by lagleki** [Tatoeba/tatoeba2#612] opened 2015-03-11 11:10 UTC
in "http://tatoeba.org/eng/sentences_lists/show/" urls translate button isn't shown near the infoIcon.

Since some of us use list to translate sentences one by one it'd be nice to have Translate button there.

**Comment by trang** [comment] 2015-03-27 21:54
Duplicate of #117.

**Closed by trang** 2015-03-27 21:54 UTC
