### ISSUE TITLE
Some advanced searches get an internal error message

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2635] opened 2021-03-06 06:11 UTC
An Internal Error Has Occurred
Error: An Internal Error Has Occurred.

Here's a link to one that does. (pre-filled search form)

https://tatoeba.org/eng/sentences/advanced_search?from=eng&has_audio=yes&list=907&native=&orphans=no&query=&sort=words&sort_reverse=&tags=&to=none&trans_filter=exclude&trans_has_audio=&trans_link=&trans_orphan=&trans_to=mon&trans_unapproved=&trans_user=&unapproved=no&user=

**Comment by jiru** [comment] 2021-03-07 15:44
Closing as a duplicate of #1737.

**Closed by jiru** 2021-03-07 15:44 UTC
Labels: bug
