### ISSUE TITLE
Search is finding sentences that do not contain the specified word

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1944] opened 2019-08-23 02:41 UTC
Search is finding sentences that do not contain the specified word. This was reported 24 days ago (see link 1 below), and @gillux made a change that he thought might have fixed the problem, but apparently it didn't. For instance, a general search for "Tom" in English (see link 2 below) brings up these sentences:

Damn.
#1078143

Beat it.
#37902

Damn you!
#1135061

We talked.
#2107672

How unfortunate!
#2111810

These sentences are owned by a variety of people, and the logs don't reveal anything that suggests that they ever contained the word "Tom". Nor do all the sentences contain a tag, or audio. However, they are all short. If I set the sort order to random or to longest sentences first, I don't see any false hits.

Could it be that the search engine has seen so many sentences with "Tom" that it now hallucinates them even in sentences that don't contain the word?

I reported this on the Wall as well: 

https://tatoeba.org/eng/wall/show_message/32491#message_32491

Link 1: https://tatoeba.org/eng/wall/show_message/32265#message_32265

Link 2: https://tatoeba.org/eng/sentences/search?query=tom&from=eng&to=none&orphans=no&unapproved=no&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words

**Comment by trang** [comment] 2019-08-24 16:40
I'm currently re-creating all the indexes. I had plans to do it back in https://github.com/Tatoeba/tatoeba2/issues/1631#issuecomment-517942994 but hadn't yet. We'll see what happens after...

For the record, below are some other searches that contain wrong results on the first page.

- https://tatoeba.org/eng/sentences/search?query=butter&from=eng&to=und
  * Good job! 
  * He's well built. 
  * Get the fuck out! 
  * Perhaps you're right. 
  * Blow out the candles. 
- https://tatoeba.org/eng/sentences/search?query=damn&from=eng&to=und
  * Go away!
- https://tatoeba.org/eng/sentences/search?query=talked&from=eng&to=und
  * Stop them.
- https://tatoeba.org/eng/sentences/search?query=unfortunate&from=eng&to=und
  * Did Tom respond?
- https://tatoeba.org/eng/sentences/search?query=good&from=eng&to=und
  * Beat it.
- https://tatoeba.org/eng/sentences/search?query=away&from=eng&to=und
  * Good heavens!
- https://tatoeba.org/eng/sentences/search?query=perhaps&from=eng&to=und
  * It's great.
- https://tatoeba.org/eng/sentences/search?query=histrionic&from=eng&to=und
  * Were you drunk?
- https://tatoeba.org/eng/sentences/search?query=were&from=eng&to=und
  * What jerks!

**Comment by trang** [comment] 2019-08-26 14:46
The problem re-emerged. [Brauchinet reported the issue](https://tatoeba.org/eng/wall/show_message/32515#message_32515) with the search "islamophobia".

Below is the date and time of creation of each sentence in the results.

```
MariaDB [tatoeba]> select id, created, text from sentences where id in (7851749, 8113164, 8130106, 8130110, 8130111, 8130121, 8130123, 8130214) order by id;
+---------+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id      | created             | text                                                                                                                                                                                              |
+---------+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7851749 | 2019-04-14 18:18:12 | Everyone knows the separatists for their rabid racism and Islamophobia.                                                                                                                           |
| 8113164 | 2019-08-17 23:57:10 | Both Ilhan and Rashida strongly oppose all forms of racism, tribal quarrels and racial hatred, whether Islamophobia, anti-Semitism or the xenophobic detention and deportation of asylum-seekers. |
| 8130106 | 2019-08-25 16:10:50 | Islamophobia is a problem that's on the rise.                                                                                                                                                     |
| 8130110 | 2019-08-25 16:13:17 | Islamophobia is a real problem.                                                                                                                                                                   |
| 8130111 | 2019-08-25 16:14:10 | A group of skinheads gathered near the mosque.                                                                                                                                                    |
| 8130121 | 2019-08-25 16:15:33 | Is this a racist statement?                                                                                                                                                                       |
| 8130123 | 2019-08-25 16:15:45 | Let's study Islamic history.                                                                                                                                                                      |
| 8130214 | 2019-08-25 16:50:07 | A driver blocked the intersection.                                                                                                                                                                |
+---------+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
8 rows in set (0.00 sec)
```

Below are the sentences that should normally have been in the results:
```
MariaDB [tatoeba]> select id, created, text from sentences where text like '%Islamophobia%' order by id;
+---------+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id      | created             | text                                                                                                                                                                                              |
+---------+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7851749 | 2019-04-14 18:18:12 | Everyone knows the separatists for their rabid racism and Islamophobia.                                                                                                                           |
| 8113164 | 2019-08-17 23:57:10 | Both Ilhan and Rashida strongly oppose all forms of racism, tribal quarrels and racial hatred, whether Islamophobia, anti-Semitism or the xenophobic detention and deportation of asylum-seekers. |
| 8130096 | 2019-08-25 16:09:02 | This talk is about Islamophobia.                                                                                                                                                                  |
| 8130097 | 2019-08-25 16:09:11 | What is Islamophobia?                                                                                                                                                                             |
| 8130099 | 2019-08-25 16:09:20 | Islamophobia is dangerous.                                                                                                                                                                        |
| 8130106 | 2019-08-25 16:10:50 | Islamophobia is a problem that's on the rise.                                                                                                                                                     |
| 8130110 | 2019-08-25 16:13:17 | Islamophobia is a real problem.                                                                                                                                                                   |
| 8130181 | 2019-08-25 16:31:11 | Islamophobia is a danger.                                                                                                                                                                         |
+---------+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
8 rows in set (5.29 sec)
```

I ran `indextool --check eng_main_index` and there are [90 failures reported](https://gist.github.com/trang/34281a451a8e875fffb72dd27ef467d2).

**Comment by trang** [comment] 2019-08-27 18:54
Yes, I saw it, but this is not a systematic pattern. He mentioned that it doesn't work for the sentence "Kiev is the capital of Ukraine." in the [Colombia](https://tatoeba.org/eng/sentences/search?query=Colombia&from=eng&to=und) search.

I found out that "I live in Colombia" was the sentence being replaced by "Kiev is the capital of Ukraine". So I chained the searches, using the wrong search result as my next search. This is the chain I obtained:

ID | Sentence
-- | --
7871467 | I live in Colombia.
7909051 | Kiev is the capital of Ukraine.
7967473 | I wonder whose this is.
7973986 | How much are a dozen eggs?
7984831 | Why does Tom want to live in Boston?
8009797 | Mennad doesn't dress this way.
8034851 | Mennad farted again.
8047791 | Mennad is so sweet.
8098829 | Tom pooped his pants at his sister's wedding.
8111396 | I will never eat meat again.
8117954 | At four o'clock he went to the barber.
8127465 | The privacy settings on your smartphone allow this application to track your whereabouts.

From what I've checked, the gap between each sentence is not consistent, even if you only count English sentences. The only thing that seems consistent is that older sentences are being replaced by more recent sentence. What triggers this replacement is still a mystery.

Also, it seems only English is afftected. I'm not sure what's wrong with English specifically... The other languages that are in the top 15 do not have a corrupted index. I also checked randomly some of the less popular languages and didn't find any that had a corrupted index.

**Comment by jiru** [comment] 2019-08-28 20:18
Since old sentences are being replaced by new ones, I suspect it has something to do with the delta/main indexes thing. The bug could be happening when main+delta indexes are merged (index merges are scheduled daily, if I remember correctly). You could try to run the merge manually to check if the merge tool shows a strange behavior. Or try to disable merge in the crontab for some time, to confirm it triggers the bug. Disabling merge shouldn't break anything, just maybe put some more load on the server.

Now I remember that the last upgrade of Manticore [introduced a change](https://manticoresearch.com/2019/05/15/how-kill-lists-changed-in-manticore-search-3/) in the way the way kill lists are handled. I had to adjust the config file accordingly, maybe I did something wrong.

Still, it doesn't explain why only English is affected. (The only difference I can see is that it's the only language with more than 2^20 sentences.) It could be worth reporting this problem to the Manticore team, although tricky to provide them with a reproducible scenario.
-- gillux

**Comment by brauchinet** [comment] 2019-09-04 18:46
Interestingly, every single word in the manticore_indextool failure list [https://gist.github.com/trang/34281a451a8e875fffb72dd27ef467d2] is contained in one of these six consecutive English sentences:

#8131026  I want to become a famous artist.
#8131027 Tom is getting on his horse right now.
#8131028  That's the wrong way to do that.
#8131029  Tom is getting ready to take a shower.
#8131030  I want to become a famous singer.
#8131053 The farmer feeds alfalfa to his dairy cattle.   (2019-08-26 03:58:01)

**Comment by brauchinet** [comment] 2019-09-13 10:56
I just checked some searches at random:
- Islamophobia from the search above has only 7 results now (8130181 is missing).
- Some of the sentences from my previous comment are not found (eg. 8131053 which is notable for its very specific vocabulary , 8131029)

**Comment by trang** [comment] 2019-09-15 14:20
So something wrong is happening already before the index merge.

I actually noticed that [searching for all sentences](https://tatoeba.org/eng/sentences/search?query=&from=und&to=und&orphans=&unapproved=&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=relevance) returns a count higher than the actual number of sentences. There's about 10k of difference.
- 7811029 occurrences in the search
- 7799893 sentences from the stats

I'm starting again af full reindexation. I have disabled both delta indexing and index merge. Will check if the number of occurences is correct or not. It should match these stats: https://gist.github.com/trang/eb29e33b5133b6179739554a491c8df9

**Comment by jiru** [comment] 2019-09-15 15:57
@Trang Thanks for troubleshooting this! About the total number of sentences, remember that Manticore does not index sentences with unknown language, so you should exclude them from the SQL count.
-- gillux

**Comment by trang** [comment] 2019-09-16 21:26
From what I've checked, the number of occurences returned by the search is always higher than it should be. The difference is more significant the more sentences there are.

Lang | search count | db count (cf. [gist](https://gist.github.com/trang/eb29e33b5133b6179739554a491c8df9))
-- | -- | -- 
eng | 1231886 | 1220425
ita | 732780 | 729476
rus | 719079 | 713691
tur | 679226 | 674888
epo | 606112 | 602893
deu | 479222 | 475826
fra | 402139 | 398937
por | 337983 | 335893
spa | 313305 | 311332
swe | 35259 | 35033
hin | 12489 | 12091
tuk | 6753 | 6724 
ilo | 2462 | 2454
nno | 1332 | 1325
tha | 1190 | 1190 
gla | 1005 | 1005 
sah | 926 | 926
uzb | 680 | 680
nov | 311 | 311

There doesn't seem to be any issue below 1000 sentences. Not sure if something wrong is happening during the main indexation or if the way Manticore counts isn't reliable on high occurences.

**Comment by AndiPersti** [comment] 2019-09-17 05:09
How did you obtain the numbers in "search count"?

I seems to me the counting in the search code doesn't work:
If I use a [simply search for Ilocano](https://tatoeba.org/eng/sentences/search?query=&from=ilo&to=und) I get 2461 occurrences.
If I change the [sort order to "Last created first"](https://tatoeba.org/eng/sentences/search?query=&from=ilo&to=und&orphans=no&unapproved=no&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=created) I get 2666 occurrences.
If I change the [sort order to "Last modified first"](https://tatoeba.org/eng/sentences/search?query=&from=ilo&to=und&orphans=no&unapproved=no&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=modified) I get 2465 occurrences.
And the sort order "Random" is really random for me (I get 2465, 2467, 2468, ...) if I reload the page.

There is also a difference when the sort order is "Relevance" and I toggle the direction using the "Reverse order" checkbox (2461 and 2466).

What numbers do you get when you query the Manticore tables directly (e.g. `echo "select count(*) from ilo_main_index;" | mysql -h0 -P9306`)?

**Comment by trang** [comment] 2019-09-17 23:13
> How did you obtain the numbers in "search count"?

From the advanced search, with "Is orphan" and "Is unapproved" are both set to "Any". In other words, using [this URL](https://tatoeba.org/eng/sentences/search?query=&from=und&to=und&orphans=&unapproved=&user=&tags=&list=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=relevance), but changing `from=und` to `from={lang}`.

> What numbers do you get when you query the Manticore tables directly (e.g. echo "select count(*) from ilo_main_index;" | mysql -h0 -P9306)?

I get 2454 for the count on ilo_main_index.

I ran the queries on the main and delta indexes for some of the languages. The numbers are pretty close to the db count for the *_main_index. The difference between the search count and db count seem to match more or less the count of the delta_index.

Lang | search count | db count | main_index | delta_index
-- | -- | -- | -- | --
eng | 1231886 | 1220425 | 1220423 | 11556
ita | 732780 | 729476 | 729480 | 3332
rus | 719079 | 713691 | 713700 | 5433
tur | 679226 | 674888 | 674901 | 4347
epo | 606112 | 602893 | 602898 | 3249
ilo | 2462 | 2454 | 2454 | 21
uzb | 680 | 680 | 680 | 6
nov | 311 | 311 | 311 | 3

I'm a bit confused why the delta_index count is not at zero though. I tried to `bin/cake sphinx_indexes merge` to see if it would change anything, but it didn't.

I then ran `bin/cake sphinx_indexes update delta`. The main_index, delta_index and search count changed as followed.

Lang | search count | db count | main_index | delta_index
-- | -- | -- | -- | --
eng | 1220884 | 1220425 | 1216163 | 4721
ita | 729495 | 729476 | 727734 | 1761
rus | 714302 | 713691 | 711696 | 2606
tur | 675161 | 674888 | 673108 | 2053
epo | 606112 | 602893 | 601670 | 1584
ilo | 2454 | 2454 | 2444 | 10
uzb | 680 | 680 | 677 | 3
nov | 311 | 311 | 310 | 1

**Comment by jiru** [comment] 2019-09-26 16:25
> I'm a bit confused why the delta_index count is not at zero though. I tried to `bin/cake sphinx_indexes merge` to see if it would change anything, but it didn't.

This is the expected behaviour. That command merely performs `main = merge(main, delta)`, leaving the delta index untouched. The delta index will only shrink the next time it is refreshed.

> I just checked some searches at random:
> 
>   * Islamophobia from the search above has only 7 results now (8130181 is missing).
>   * Some of the sentences from my previous comment are not found (eg. 8131053 which is notable for its very specific vocabulary , 8131029)

> So something wrong is happening already before the index merge.
> 
> I actually noticed that searching for all sentences returns a count higher than the actual number of sentences.

I think you’re looking at a different problem, that may or may not be related.

As far as I understand, the problem initially reported was not about the number of results, but about search results containing sentences not matching the search query. In particular, the number of results were unchanged, as if some sentences were replaced by others in the search results, [as shown by Trang earlier](https://github.com/Tatoeba/tatoeba2/issues/1944#issuecomment-524889904). I also noticed the same symptom [when I first discovered the bug](https://tatoeba.org/jpn/wall/show_message/32277#message_32277): the number of search results did not change before and after I rebuilt the English index, while the contents of the results did.

Since that particular bug hasn’t been reported so far since [Trang disabled index merge](https://github.com/Tatoeba/tatoeba2/issues/1944#issuecomment-530917298), I think it is safe to assume that index merge is causing the problem. Besides, `indextool --check` is not reporting any problem now.

We’ve been performing index merge daily, so I suspect that the index gets corrupted during a particular merge and that subsequent merges do not solve the problem. Since it looks like `indextool` is a good indicator of the presence of the bug, I’ve restored daily index merge and I set up some automatic monitoring that will notice me if `indextool` starts to complain. From there, maybe we can better debug the issue with `indextool --dumpdocids` or at least keep a copy of the corrupted index to give to the Manticore team. I’ll keep you updated! :+1:

**Comment by jiru** [comment] 2019-09-27 07:14
> Interestingly, every single word in the manticore_indextool failure list is contained in one of these six consecutive English sentences:
> 
> #8131026 I want to become a famous artist.
> #8131027 Tom is getting on his horse right now.
> #8131028 That's the wrong way to do that.
> #8131029 Tom is getting ready to take a shower.
> #8131030 I want to become a famous singer.
> #8131053 The farmer feeds alfalfa to his dairy cattle. (2019-08-26 03:58:01)

Good catch, @brauchinet. This is consistent with index merge that is triggered daily at 04:01:00, beginning with Arabic index, English index, and then others. The next English sentence (#8131056) has been created at 04:01:51, which is very likely just after the English index was merged on that day.

**Comment by jiru** [comment] 2019-09-27 08:06
Maybe the problem is due to a race condition between index merge and refresh. As an attempt to prevent both from happening at the same time, I made it so that the index merge script always waits for any running index refresh to finish before starting. As a result, we always start index merge *right after* the delta index refresh script finishes.

However, after an index refresh, the SIGHUP signal is sent to searchd, that picks up all the newly-created index files suffixed with `.new`. For example `eng_delta.new.spa` would be renamed into `eng_delta.spa` (see the `--rotate` option of `indexer`). By the time the SIGHUP signal is received and processed by searchd, the merging script may have already started to read delta index files too.

What’s more, there is not only a `.spa` file but also [a dozen of other files](https://docs.manticoresearch.com/latest/html/indexing/indexes.html#index-files) involved for each index, which increases the risk of a race condition. The English index being the largest one, it also makes it more prone to such race condition. That would explain why `indexer --check` only reported errors in the English index.

**Comment by jiru** [comment] 2019-10-01 06:44
"indexer --check" is reporting errors on the English index now.

**Comment by jiru** [comment] 2019-10-01 19:36
This time indextool reported [different errors](https://gist.github.com/jiru/5e54a0806ef4335a3e6dbf100881fe8b). Other logs didn’t show anything relevant. I saved the faulty index just in case and rebuilt the English index.

As an attempt to work around that potential race condition, I added the `--sighup-each` flag for delta reindexation. Now we have to wait to see if the bug happens again.

**Comment by jiru** [comment] 2019-10-28 06:28
It has been a long enough time without indextool reporting errors. I think it is safe to assume that the problem has been solved by the workaround.

**Closed by jiru** 2019-10-28 06:28 UTC
Labels: bug
