### ISSUE TITLE
number of sentences in non-empty list sometimes displayed as zero

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1775] opened 2019-02-07 03:37 UTC
I have 100 sentences in my list [Rus (19): worth learning: private
created by AlanF_US](https://tatoeba.org/eng/sentences_lists/show/8682), and when I look at the list, I see all 100 sentences and the "About this list" box says "Contains 100 sentences". However, from the [list of my lists](https://tatoeba.org/eng/sentences_lists/of_user/AlanF_US), the number is displayed as 0 (which gave me a shock, since I thought I had somehow mistakenly deleted them from the list).

**Comment by ckjpn** [comment] 2019-02-08 05:27
Related maybe:

https://github.com/Tatoeba/tatoeba2/issues/1769

**Comment by trang** [comment] 2019-02-16 13:18
Duplicate of #1769 indeed. I'll close this issue and keep the other one.

**Closed by trang** 2019-02-16 13:18 UTC
