### ISSUE TITLE
Same tags appearing in different pages

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1594] opened 2018-07-02 22:20 UTC
When browsing tags, some of them are duplicated in different pages. For example, the tag "by Ovid" is appearing both here https://tatoeba.org/ita/tags/view_all/by/page:3 and here https://tatoeba.org/ita/tags/view_all/by/page:4

There are some other examples when browsing all the tags containing "by"

**Comment by trang** [comment] 2018-08-26 01:06
Cannot reproduce. I believe this has been fixed with https://github.com/Tatoeba/tatoeba2/commit/d749e3b8f3a63c8af0319f033bcef78cbfcfc289.

**Comment by AndiPersti** [comment] 2019-08-16 12:49
I can reproduce this bug locally.

Here is my `tags` table:
````
MariaDB [tatoeba]> select id, name, nbrOfSentences from tags order by nbrOfSentences;
+----+-------+----------------+
| id | name  | nbrOfSentences |
+----+-------+----------------+
| 13 | tag13 |              1 |
|  2 | tag2  |              1 |
|  4 | tag4  |              1 |
|  6 | tag6  |              1 |
| 12 | tag12 |              2 |
| 10 | tag10 |              2 |
|  1 | tag1  |              2 |
|  5 | tag5  |              2 |
|  3 | tag3  |              2 |
|  8 | tag8  |              3 |
|  7 | tag7  |              3 |
|  9 | tag9  |              4 |
| 11 | tag11 |              4 |
+----+-------+----------------+
13 rows in set (0.00 sec)
````
Now let's introduce pagination (pages contain 3 items):
````
MariaDB [tatoeba]> select id, name, nbrOfSentences from tags order by nbrOfSentences limit 3;
+----+------+----------------+
| id | name | nbrOfSentences |
+----+------+----------------+
|  2 | tag2 |              1 |
|  4 | tag4 |              1 |
|  6 | tag6 |              1 |
+----+------+----------------+
3 rows in set (0.00 sec)
````
This looks fine so far but notice that the first tag is `tag2` and not `tag13` as when selecting all rows. Next page:
````
MariaDB [tatoeba]> select id, name, nbrOfSentences from tags order by nbrOfSentences limit 3 offset 3;
+----+-------+----------------+
| id | name  | nbrOfSentences |
+----+-------+----------------+
| 13 | tag13 |              1 |
|  1 | tag1  |              2 |
|  3 | tag3  |              2 |
+----+-------+----------------+
3 rows in set (0.00 sec)
````
Still no problem but again `tag1` wasn't the first row with 2 sentences in the big table. Next page:
````
MariaDB [tatoeba]> select id, name, nbrOfSentences from tags order by nbrOfSentences limit 3 offset 6;
+----+-------+----------------+
| id | name  | nbrOfSentences |
+----+-------+----------------+
|  5 | tag5  |              2 |
|  3 | tag3  |              2 |
| 10 | tag10 |              2 |
+----+-------+----------------+
3 rows in set (0.00 sec)
````
Now `tag3` appears a second time.

The reason is that several tags have the same number of sentences linked to them and the order within this group of tags is arbitrary and not stable when querying the database consecutively as pagination does. Now when the tags in that group are split so that one part is at the end of a page and the other at the beginning of the following page it is possible that one tag may appear at both pages.

**Closed** 2019-08-20 17:13 UTC
Labels: bug
