### ISSUE TITLE
The tagName doesn't  currently show at the top of pages showing the list of tags.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1990] opened 2019-10-17 00:28 UTC
Screenshots for these two are shown below.

https://tatoeba.org/eng/Tags/show_sentences_with_tag/9789/

https://tatoeba.org/eng/tags/show_sentences_with_tag/1097

<img width="763" alt="Screen Shot 2019-10-17 at 9 26 12" src="https://user-images.githubusercontent.com/7934273/66968506-6a573d00-f0c0-11e9-8f9f-65763605c00a.png">

<img width="761" alt="Screen Shot 2019-10-17 at 9 25 22" src="https://user-images.githubusercontent.com/7934273/66968507-6a573d00-f0c0-11e9-9b39-e0fddc1a09e9.png">

**Comment by AndiPersti** [comment] 2019-10-17 04:54
Duplicate of #1987.

Will be fixed with the next update.

**Closed** 2019-10-20 10:35 UTC
