### ISSUE TITLE
List Sorting direction=desc doesn't work and is the same as direction=asc

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1803] opened 2019-02-28 06:13 UTC
Before clicking the "date added to list" a second time reversed the sort.
Now that doesn't happen.

Also, these URLs now get the same sort.

https://tatoeba.org/eng/sentences_lists/show/8760/und?sort=created&direction=desc
https://tatoeba.org/eng/sentences_lists/show/8760/und?sort=created&direction=asc

**Comment by AndiPersti** [comment] 2019-08-15 06:41
@ckjpn Is this still a problem for you?

I've tried to reproduce this issue, but both your links (and others I've tried) work for me, i.e. they show the sentences in descending and ascending order respectively. Also clicking on either "date added to list" and "date created" will reverse the current ordering.

(I couldn't find any commits since February 28th which would explain the fix for this issue but I've probably looked at the wrong places.)

**Comment by trang** [comment] 2019-08-22 21:54
Can't reproduce either and I don't think we did anything in particular to fix it. Might have been fixed by upgrading the CakePHP version...

I think it's safe to close.

**Closed by trang** 2019-08-22 21:54 UTC
Labels: regression
