### ISSUE TITLE
Make it possible to limit search results to  sentences that contain a word in the target language and another word in translations of another language.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1924] opened 2019-07-20 00:25 UTC
## The Suggestion
Make it possible to limit search results to  sentences that contain a word in the target language and another word in translations of another language.

Additionally, have the option to use only the minus (-) operator in search results, so all sentences except those with translations containing a certain word would be shown.

This was the implied suggestion in a message that came into team@tatoeba.org.

## The Problem

> Hi, I have a small problem.
> 
> Take for example the word 'da' in German, it can mean a lot of things 
'since', 'there', 'then', etc...
> 
> I want to only show sentences that contain 'da' in German, but when it 
means 'since' not 'there', etc..
> 
> I think it would be great to have an option to exclude translation that 
don't contain a specific word. In my case 'since'.

**Comment by jiru** [comment] 2019-07-23 11:20
Thank you, CK. I’m closing this issue as it is a duplicate of #1576.

**Closed** 2019-07-24 11:21 UTC
