### ISSUE TITLE
An easier way to create lists

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#929] opened 2015-11-20 02:07 UTC
It was discussed on the Wall - https://tatoeba.org/eng/wall/show_message/24903#message_24903
It would be easier if we create lists as we tag sentences. (https://tatoeba.org/eng/wall/show_message/24914#message_24914)

Many people tag sentences since it's the easiest way to create a list and add sentences on it. Is that to do the same to the actual lists? Instead of clicking in order to tag each of them to a(some) specific list(s), have a system that would do the same? Maybe we could have a new "lists system" by having those "tags" in a different color.

E.g.: "less than 8 words" is a tag, so it would be considered as a tag and added as a tag and could be browsed in the "Browse tag" section since it would be used by everyone.

"Studying English - Ricardo14" is a list. So it would considered and added as a list and could be browsed in the "Browse by lists" section since just one a very small group of members would use it. Maybe having an extra field. Something like this ► 
![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/11290099/8e63fba4-8f1a-11e5-9eef-a1356aa71886.png)

**Comment by ckjpn** [comment] 2015-11-20 12:35
> Many people tag sentences since it's the easiest way to create a list and add sentences on it. Is that to do the same to the actual lists? 

I don't think this is true.  Trang specifically asked that things that should be on list should not be done as tags.  (It's in a blog post somewhere.)

Choosing a list from the pull down menu of lists isn't that hard.  I do it all the time.
In some ways, it's easier than tagging, since you don't have to type anything.

Unless I've misunderstood his request, I think this request should be ignored.

I think there is a danger of getting the pages so cluttered with features that they will be less effective.  Sometimes, simple is best.  If it's not a feature that a majority of the members would use, then perhaps it's better not put on the page.

I think this mostly unnecessary enhancement may just also cause unneeded extra work for the programmers.

If it's easy to do, doesn't slow down the pages, and many of the members want it, then I have no real objection to adding such a feature.

**Comment by RyckRichards** [comment] 2015-11-20 12:58
I don't know if I was clear when I sad that the lists WON'T become tags,
but as far as many some people tag in order to create lists (c.f. names of
languages, some dates, etc).
I do know that we need a lot of programmers and I am working on it. I am
also studying this myself. Besides, it was not posted here to be
implemented now. It was just an idea that come to.mind.while I was
discussing about it (check the link above).

**Comment by jiru** [comment] 2015-11-22 19:10
@RyckRichards, I’m having trouble understanding your idea.

While looking at your edited screenshot, I don’t really understand the difference between your idea and the current system with the “add to list” button that shows a drop-down menu.

What’s your proposing is to allow to add to a list all the sentences that have a given tag, right? For instance, I create a list called “blah”, then I have some form on the list page in which I enter “less than 8 words”, and all the sentences that have that tag get added to the list “blah”. Is that what you’re having in mind?

**Comment by RyckRichards** [comment] 2015-11-22 19:40
Sorry, I didnt explain that properly.

That's what we have now:
To create a tag, all you gotta is  to type something on the "tags" field
such as OK, simple present,etc

For lists: to create lists, choose "Browse by list" on menu bar and on
there, create a list. And to add sentences, you have to click on that icon.

My idea: use the same system that we use for tags to lists. (actually, add
this option to create lists and add sentences in there). This way, I
wouldnd have to browse by list and click to both add sentences on a
list/create lists. I would have this option too but I could easily add a
certain sentence to a list by "tagging" it

**Comment by trang** [comment] 2020-02-14 23:55
I would say this is a duplicate of  #161, except it's suggesting a different solution. 

The solution in #161 is better in my opinion because we can make it possible to create new lists without having to go to the sentence's page.

I'm closing this, but feel free to re-open if there's something I have overlooked in this one.

**Closed by trang** 2020-02-14 23:55 UTC
Labels: enhancement
