### ISSUE TITLE
"An Internal Error Has Occurred" when listing a list with all translations

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2897] opened 2022-01-26 07:53 UTC
This gets the error message.
https://tatoeba.org/en/sentences_lists/show/169970/und

This one doesn't.
https://tatoeba.org/en/sentences_lists/show/169970/eng

Wednesday, January 26, 2022 at about 07:50

**Comment by jiru** [comment] 2022-04-11 09:10
Could be a duplicate of #2888.

**Closed** 2022-04-17 18:34 UTC
Labels: bug
