### ISSUE TITLE
North Moluccan Malay (max)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#799] opened 2015-10-05 11:10 UTC
* Language name: North Moluccan Malay
* Language info: https://en.wikipedia.org/wiki/North_Moluccan_Malay
* ISO 639-3 code: max
* Public List: https://tatoeba.org/eng/sentences_lists/show/4714
* Icon: https://drive.google.com/file/d/0B6VpA-j8A4f9Z1NrRmx2QUNTTTByVTBVUmJsRDlGMllVMTh3/view?usp=sharing
* Requested by: **cueyayotl** https://tatoeba.org/eng/user/profile/cueyayotl

**by** @Guybrush88 
> annotation: yatyayat (https://tatoeba.org/ita/user/profile/yatyayat) says he/she is a native speaker

TODO
`CALL add_new_language('max', 4714);`

**Comment by Guybrush88** [comment] 2015-10-05 11:29
duplicate of: https://github.com/Tatoeba/tatoeba2/issues/792

**Comment by Guybrush88** [comment] 2015-10-05 12:27
annotation: yatyayat (https://tatoeba.org/ita/user/profile/yatyayat) says he/she is a native speaker

**Closed** 2015-10-13 19:22 UTC
Labels: lang_request
