### ISSUE TITLE
Merge sentences that differ only in punctuation and spacing

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#642] opened 2015-05-07 12:11 UTC
Ideally, the duplicate-merging script could merge sentences that differ only in punctuation (including apostrophes) and spacing. There are two possibilities: (a) merge sentences that differ only in "equivalent" punctuation (e.g., straight quotes vs. curly quotes, regular spaces vs. non-breaking spaces) or (b) merge sentences that differ only in punctuation, but without restriction on the punctuation (so a sentence ending with a period would be merged with a sentence ending with an exclamation mark). 

There are also at least two approaches:

(1) Agree on a standard "canonical" set of punctuation marks and spaces, and convert "noncanonical" ones to canonical ones at the time the sentences are added. (There would also need to be a pass to convert legacy sentences once this change was instituted.) Example: for English, declare that straight quotation marks are canonical and that curly quotation marks will be converted into straight ones.

(2) Rather than agreeing on canonical punctuation marks, agree on ones that will be treated equivalently by the script, and let the standard rules determine which sentence wins (for instance, in the absence of other factors, the older sentence wins).

The problem is that the discussion generally bogs down at this point. There are some people who really like the idea of canonical punctuation and some people who hate it -- and some of the people who like it can't agree with others about what should be canonical. For instance, should straight quotation marks be canonical because they're easier to type and easier to process (no need to figure out whether they're opening or closing marks)? Or should curly quotation marks be canonical because they're traditional, and are the form that appears in books? Such decisions would potentially have to be made for every language. Approach 2 cuts down on the pain of having to reach agreement as to which ones "win", but we still would need to identify sets of equivalent characters (though potentially we could use one set across all languages).

**Comment by alanfgh** [comment] 2015-05-07 12:13
See #557 for a list of some sentences that were not merged. The list contains some that differ in the presence of a byte-order mark (which are not relevant to this discussion), but those can be ignored.

**Comment by ckjpn** [comment] 2015-06-20 23:22
> (b) merge sentences that differ only in punctuation, but without restriction on the punctuation (so a sentence ending with a period would be merged with a sentence ending with an exclamation mark).

This should be avoided, since this might delete the better of the two.

For example, a native speaker has the sentence with an exclamation mark, but a non-native speaker has one with a period, or visa versa.  This could happen between 2 native speakers, too, of course.)

At least in English, there are cases where one would be the better example to keep.

That said, it might be OK to have all such sentence automatically linked, so that indirect translations can be seen.

**Comment by Guybrush88** [comment] 2015-10-21 20:59
concerning French, a possible solution has been proposed here: https://tatoeba.org/ita/wall/show_message/24674#message_24674

**Comment by ckjpn** [comment] 2015-10-21 21:15
I can't read the French on the Wall, so maybe this is a duplicate of what the Wall posts say.

Concerning the French, I think we need a script that goes through and standardizes this space, so the duplicates get deleted and their translations all get merged.

I think Trang can probably choose whichever space she thinks is best and use it, even if everyone doesn't agree on which space if best.  As long as it's standard, anyone using the data can likely easily do a mass "find and replace" to convert the space to what they want it to be.

I think the same script could also be used for correcting some basic mistakes that we often see on the site like (primarily) French members mistakenly inserting spaces before final punctuation in English sentences.

**Comment by Guybrush88** [comment] 2015-10-21 21:39
in brief, for French, this space: http://www.fileformat.info/info/unicode/char/202f/index.htm should be used before some punctuation like :, ? or !

**Comment by jiru** [comment] 2015-11-11 17:30
First, I’m against merging sentences that differ in punctuation. “You’re hungry.” is not the same as “You’re hungry?”. Only typography differences should be taken into account. I think we all agree on this but I just wanted to point it out since the title of the issue can be misleading.

I’m in favor of approach 2 because:
* French typography is [infinitely more complex](http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?t1=1&id=2039). As you may see in this link, you may even insert or remove spaces depending on the context, intended meaning or just personal preference (whether you consider no space is better than a space that is not *fine*). It’s nothing that can be turned into a safe algorithm. That said, a minimal set of rules would likely cover the majority of duplicates. Still, some would require manual merge.
* It’s way easier to avoid making decisions. If Trang is in position to decide upon a standard typography for the French corpus of Tatoeba, who will decide for all the other languages? Who will take the responsibility?
* It’s easier to implement.
* Generally speaking, I believe tools should adapt to languages, not the opposite.
* People who want consistent typography can still download the corpus and mass-edit it the way they want.

**Comment by alanfgh** [comment] 2015-11-11 23:31
I agree that "You're hungry." does not have the same meaning as "You're hungry?". Furthermore, translations for one might not work as translations for the other. But, at least in English, where we're talking not about "period vs. question mark" sentence pairs, but "period vs. exclamation mark" pairs, or "presence vs. absence of optional comma" pairs, both members of the pair would usually be translated the same way, exclusive of punctuation. There are huge numbers of such pairs, and by default, they're not linked, so users who see that "You're hungry." has no existing translations into language A might not realize that "You're hungry!" does have a translation that could serve for both. 

There are other ways this problem could conceivably be handled. Rather than merging the sentences in these pairs, we could have the search engine perform a search for sentences in the same language that contain the same words in the same order (though not necessarily with the same punctuation or capitalization), and display these in proximity to the original sentence as a different kind of linked sentence. (Whether or not this is feasible is a different question.)

Obviously, both punctuation and capitalization occasionally disambiguate sentences ("That's polish" vs. "That's Polish", for instance), so there will be problematic cases. This argues for an approach more for a "display both" than a "merge".

Or we could continue not to deal with these kind of duplicates at all. I'm just putting the possibilities out there. But I'm writing this comment to explain why I gave this ticket the title that I did.

One more thing to keep in mind: this is more of an issue for contributors/translators than for other users.

**Comment by ckjpn** [comment] 2015-11-12 03:18
Concerning periods vs. exclamation marks in English, as Alan says often these would be translated the same into other languages.  However, I'd hate to see periods get replaced with exclamation marks. I've noticed a lot of non-native English speakers on tatoeba.org tend to overuse exclamation marks when writing in English.  I think that the reason for this is that perhaps in some languages the exclamation mark is required in some cases where we would perhaps not normally use them in an out-of-context, stand-alone sentence example in English.  In some case, of course, exclamation marks may perhaps would also be what a native English speaker would normally write, even though I think we see cases on tatoeba.org where even native English speakers tend to just use whatever final punctuation was used in the language they were translating from.

I think one approach might be to have a script that would link the 2 English sentences together.  This would at least show related indirect translations.   I can't think of any specific cases where such linking would be an error, but there are likely a few cases, but overall this should be fairly accurate and safe.

**Comment by ckjpn** [comment] 2019-06-11 08:48
Perhaps someone could clean up the apostrophes in the French sentences.

Related comment on https://tatoeba.org/eng/sentences/show/6599980#comment-1103711 .

J'ai froid. = #469786
J’ai froid. = #6599980

The apostrophe is different. That's why the duplicate-merging script didn't find this one.

In last week's export, 153,325 French sentences had the straight apostrophe (') and 6,122 had the curly one (’), so I assume that the straight one is what should be the standard for French sentences in the Tatoeba Corpus, just like for the English sentences.

**Comment by Iendis** [comment] 2019-06-26 21:20
There are more than a 1000 (possibly) of these types of duplicates; Here a full list

[fra_rep.txt](https://github.com/Tatoeba/tatoeba2/files/3331952/fra_rep.txt)

**Comment by ckjpn** [comment] 2019-06-26 23:05
1428 lines in the file, some list more than 1 duplicate.
For a comparison, Algerian Arabic, ranked 86 out of our 337 languages, has 1337 sentences.
Perhaps it's time to make working on this a priority.

**Comment by Iendis** [comment] 2019-06-27 06:07
There's also the problem with "—" and "-" in the Russian corpus.

Here a list with ~240 duplicates

[rus_rep.txt](https://github.com/Tatoeba/tatoeba2/files/3333154/rus_rep.txt)

**Comment by Iendis** [comment] 2019-06-27 07:08
And here's a list with ~2020 duplicates (there are 4088 sentences in total). They differ only on spacing or some ~equivalent punctuation.

This is how the file looks like: #id1 #id2 lang sentence1 lang sentence2

[_rep.txt](https://github.com/Tatoeba/tatoeba2/files/3333354/_rep.txt)

**Comment by trang** [comment] 2020-02-12 23:41
As we discussed in #770, we won't be automatically merging sentences that differ in space.

As for sentences that differ in punctuation, we cannot merge them since punctuation affects the meaning.

I'm closing.

**Closed by trang** 2020-02-12 23:41 UTC
Labels: enhancement
