### ISSUE TITLE
No way to specify an added sentence's language on the list page

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2304] opened 2020-05-02 18:46 UTC
Unlike the "Add new sentences" page, the list page does not allow you to specify a language for the sentences you add. That means I have to do that for each sentence, even though the sentences I add belong to the same language.

**Comment by jiru** [comment] 2020-05-03 09:38
Closing as duplicate of #1581 

Note that, in the past, the language used to be automatically detected, but it’s not working any more due to a bug. But I fixed that bug a few days ago, so this will probably become a less annoying problem after today’s update, which will include the fix.

**Closed by jiru** 2020-05-03 09:38 UTC
