### ISSUE TITLE
Buttons on lists are a little messy

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2045] opened 2019-12-26 00:21 UTC
https://tatoeba.org/eng/sentences_lists/show/9546

![image](https://user-images.githubusercontent.com/7658430/71451831-5da83280-275c-11ea-9e11-7d9211745b69.png)

**Comment by trang** [comment] 2019-12-28 10:49
I'm noticing that the audio icon is missing on the first sentence of the list. I tried to add this sentence to one of my lists, but I'm not able to reproduce the problem.

Is this perhaps caused by some addon on your side, @RyckRichards?

![Screenshot_2019-12-28 Test - Tatoeba](https://user-images.githubusercontent.com/221850/71542532-e47d2b00-2967-11ea-937c-fc521c325d8e.png)

**Comment by ckjpn** [comment] 2020-01-01 01:23
I, too, don't see this problem.

### This is his list.
<img width="986" alt="Screen Shot 2020-01-01 at 10 21 11" src="https://user-images.githubusercontent.com/7934273/71637196-b60d9180-2c80-11ea-855d-9e3359cc414b.png">

### This is one of my own that I tested, just in case ownership of a list made a difference.
<img width="995" alt="Screen Shot 2020-01-01 at 10 21 41" src="https://user-images.githubusercontent.com/7934273/71637202-bf96f980-2c80-11ea-94bb-20f916b937fd.png">

**Comment by RyckRichards** [comment] 2020-01-05 19:27
I disabled some addons and it worked. Now lists are being displayed properly.
However I ask myself if we'd need a way to make addons don't "mess" how they are displayed.

@trang  You can close this issue if you want :)

**Comment by AndiPersti** [comment] 2020-01-06 08:09
> I disabled some addons and it worked. Now lists are being displayed properly.
> However I ask myself if we'd need a way to make addons don't "mess" how they are displayed.

I don't think we can do much to prevent this. The whole point of browser extensions/addons is to "mess" with web pages (e.g. ad-blockers are used for removing ads on webpages).

Were you able to find out which addon caused this?

**Comment by trang** [comment] 2020-01-08 19:48
I will close this issue.

If you can identify which addon caused the issue @RyckRichards, we could help you figure out a way to fix the UI without having to disable the addon. Feel free to provide more information in this issue even after it's closed.

**Closed by trang** 2020-01-08 19:48 UTC
