### ISSUE TITLE
MetadataSideNavPane already up for testing?

### ISSUE THREAD

**Issue by mramosch** [Tatoeba/tatoeba2#3001] opened 2022-10-20 18:18 UTC
Is it to early in the adoption process to give feedback (I cannot remember having seen any new feature announcement)?

Because I am having some issues on iOS…

**Comment by trang** [comment] 2022-10-22 16:44
If you have issues, feel free to report. We don't always announce changes and here it's not exactly a new feature, but rather a redesign of the sentence page to make it responsive (#2959).

**Comment by Yorwba** [comment] 2022-10-23 08:50
@trang I think you might've forgotten to run the asset build when deploying to dev and the CSS was out of date.

@mramosch Please check again to see whether the issues you noticed are still present. If they are, please describe them in more detail.

**Comment by trang** [comment] 2022-10-23 16:33
> @trang I think you might've forgotten to run the asset build when deploying to dev and the CSS was out of date.

Yes, indeed.

**Comment by trang** [comment] 2022-10-25 18:47
@mramosch How exactly do you trigger the unexpected scroll behavior? If this happens when you click on the logs of a sentence in the old design, then it is actually an intended behavior. It is meant to highlight the sentence that you clicked in the logs.

**Comment by mramosch** [comment] 2022-10-25 19:03
New design, sentence page, click on !METADATA

**Comment by trang** [comment] 2022-11-03 22:07
@mramosch I created a separate issue for the scrolling (#3011) so I'll close this one 🙂 

The ugly animation might be solved if we manage to get rid of the scrolling, but if it isn't, I'm not sure if we can do much about it...

**Closed by trang** 2022-11-03 22:07 UTC
Labels: bug
