### ISSUE TITLE
reassign sentences with misspelled/mispunctuated tags

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#287] opened 2014-06-01 15:35 UTC
For instance, reassign sentences with "@needs native check." to "@needs native check". This could be done via SQL, preferably via a script.

**Comment by agrodet** [comment] 2020-04-17 14:30
If merging tags is a pinpoint operation, as I think it should be, I think this could be done by merging `@needs native check.` into `@needs native check`. The issue about merging is #961

**Comment by jiru** [comment] 2020-04-17 17:23
Closing as a duplicate of #961 (which has more information already).

**Closed by jiru** 2020-04-17 17:23 UTC
Labels: enhancement
