### ISSUE TITLE
Duplicate-merging script isn't finding some pairs.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#780] opened 2015-09-25 11:08 UTC
Duplicate-merging script isn't finding this pair.
I can't figure out how they are different.

2967925	eng	This is only the beginning.	CM
2680594	eng	This is only the beginning.	Balamax

https://tatoeba.org/eng/sentences/show/2967925

![screen shot 2015-09-25 at 20 04 37](https://cloud.githubusercontent.com/assets/7934273/10099047/0de33bcc-63c1-11e5-8744-2db7a96b1a17.png)

Here is a similar example.
https://tatoeba.org/eng/sentences/show/2269090

4185135	eng	We have to make a decision.	stevegrant
2269090	eng	We have to make a decision.	_undertoad

![screen shot 2015-09-25 at 20 18 55](https://cloud.githubusercontent.com/assets/7934273/10099247/d7d908ac-63c2-11e5-9b90-939bd4f64c82.png)

**Comment by jiru** [comment] 2015-09-25 12:12
I confirm these pairs are strictly equal. It’s likely a bug in the duplicate merger script.
```sql
mysql> select id, MD5(text), text from sentences where id in (2680594,2967925);
+---------+----------------------------------+-----------------------------+
| id      | MD5(text)                        | text                        |
+---------+----------------------------------+-----------------------------+
| 2680594 | 366c2ee764e188e45be6d218e4f2182b | This is only the beginning. |
| 2967925 | 366c2ee764e188e45be6d218e4f2182b | This is only the beginning. |
+---------+----------------------------------+-----------------------------+
2 rows in set (0.01 sec)

mysql> select id, MD5(text), text from sentences where id in (4185135,2269090);
+---------+----------------------------------+-----------------------------+
| id      | MD5(text)                        | text                        |
+---------+----------------------------------+-----------------------------+
| 2269090 | b79763b5301fa29f74df61f5b4466822 | We have to make a decision. |
| 4185135 | b79763b5301fa29f74df61f5b4466822 | We have to make a decision. |
+---------+----------------------------------+-----------------------------+
2 rows in set (0.00 sec)
```

**Comment by loolmeh** [comment] 2015-09-26 05:34
It's more likely a time period that the script never ran over than a bug...

**Comment by ckjpn** [comment] 2015-09-26 11:26
>It's more likely a time period that the script never ran over than a bug...

Does this make sense?
Both of these pairs have been there a long time, and they are still there.

**Comment by loolmeh** [comment] 2015-09-27 16:52
well it merges them just fine in a simple test case, so this is definitely not a bug...
> Both of these pairs have been there a long time

It's been a long time since a full run was actually done, there was time periods that I had to estimate manually and there might be other incidents where coverage became spotty, I'm not sure what else could be causing tbh, could you try editing one of them (that should update the modification time stamp) and see if it gets merged within 20 mins

**Comment by loolmeh** [comment] 2015-09-29 11:20
I took a harder look at this today.
1. tested the query that selects the date range, it behaves as expected in production on mysql
2. tested the specific cases you mentioned, the script behaves as expected
3. ran the script over the entire db, it merged around ~35 sentences ~25 of which had very old modification dates. A quick look at those sentences gives me the idea that some of them have been edited at a later date using some external script (bom removal script, ltr period fixing script, etc...) *after* we started using the incremental runs (so the modification timestamps are basically inaccurate). Also some of them might be due to inadequate time range coverage before the periodic runs were setup.

I'm closing this ticket for now unless there's something I can replicate and work on. I'll run the script on the entire db again next week to see if there's more sentences falling through the cracks. A more permanent solution would be adding a cron job to have a full weekly run as well, it isn't as resource intensive as it used to be.

**Closed by loolmeh** 2015-09-29 11:20 UTC
Labels: bug

**Comment by Guybrush88** [comment] 2015-10-18 09:19
same pair: https://tatoeba.org/ita/sentences/show/4243218 and https://tatoeba.org/ita/sentences/show/2700101
i manually changed mine to see if horus merges them, but i guess having a full weekly run on the whole database is the best solution for this
