### ISSUE TITLE
Possibility to delete multiple private messages at once

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1289] opened 2016-08-18 11:27 UTC
I was going through my private messages to delete some and free some space, and I noticed that I have to delete the messages one by one, so I'm suggesting that implementing a way to select and delete multiple messages at once would be really helpful and much quicker than deleting messages one by one

**Comment by zachleigh** [comment] 2016-08-20 02:57
Duplicate of https://github.com/Tatoeba/tatoeba2/issues/968

**Closed** 2016-08-28 09:24 UTC
