### ISSUE TITLE
Add Kabyle (kab) -- It's a Berber language

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1529] opened 2018-03-01 03:30 UTC
Kabyle
kab
![kab](https://user-images.githubusercontent.com/7934273/36825712-4e3262ce-1d4c-11e8-9693-73b514aa6359.png)

A new member who has already recorded over 100 audio files has requested this.
(https://tatoeba.org/eng/sentences_lists/show/7546)

All of his sentences registered at "ber" can be transferred to "kab" once you have enabled this language.
https://tatoeba.org/eng/sentences/of_user/amazigh84

Related Comments

MESSAGE 1
I've a question please, I noticed that there is another berber language defined in your database which is Tarifit from north of Morocco and of course it is "different" from mine (kabyle) but all belongs to the berber family which is in fact Tamazight, just like you may say french, italian, Spanish ... are belonging to Latin language so my question is: is it possible to change the Berber to Kabyle since all of the sentences i read are from kabyle variant ? I am asking you this because in Wikipedia this is what we have, kabyle version and other berber languages versions, which make by the end berber languages more rich i guess.

MESSAGE 2

I'm stopping the translations and waiting for adding the kabyle language, but i've one more question, since most of the sentences used actually in Berber language are in Kabyle, could we migrate them also to the new language or we need to recreate them one by one because the ID will be changed ?

Also have a suggestion: since kabyle (Taqbaylit) language, Tarifit and Targui (language of the Tuareg in desert), tachelhit and tachawit are all berber languages is may be each time a sentence is translated in one of these languages to make a duplication in the berber language if possible, so we will have finally berber langauge as the sum of all of them.

**Comment by RyckRichards** [comment] 2018-03-01 15:54
According to the Tatoeba Wiki - http://en.wiki.tatoeba.org/articles/show/new-language-request - which is attached to my profile - https://tatoeba.org/eng/user/profile/Ricardo14, this member should contact either me or cueyayotl - https://tatoeba.org/eng/private...rite/cueyayotl. I've already contacted him to know if we can add this language.

**Comment by vujma** [comment] 2018-03-03 00:56
Hi Ricardo

I didn't know to whom i should send the request, so as it is explained above, i'd like you add kabyle language in the database if possible.

Thank you.

**Comment by ckjpn** [comment] 2018-03-03 00:59
Sorry, This was my fault.  I had assumed the RyckRichards read the GitHub issues and thought that making the request directly here would be enough.

**Comment by cueyayotl** [comment] 2018-03-04 16:14
Hi all, and vujma,

I discussed this issue with Amastan (the original contributor of sentences in "Berber") a long time ago and I agree with vujma's proposition. Amastan contributed mainly in the Kabyle language, with a few exceptions (which he DOES mention in their respective comment sections). I propose the addition of "Kabyle" as a language, and a FULL migration of all of Amastan's "Berber" sentences (and possibly ALL "Berber" sentences) into "Kabyle" and eventually individually changing the sentences that are not in Kabyle.

Vujma, the eventual goal should be to not have a "Berber" language in our language list, but to have all Berber languages added individually instead. The issue is that, as you mention above, there are many of these languages, and we currently don't have the users to add sentences in all of them. We hopefully will, someday.

**Comment by trang** [comment] 2018-03-04 17:11
I will close this issue since there's another one for it: #1530.

@vujma Please be aware that the development of Tatoeba has slowed down in the past year and currently adding new languages is not the highest priority. I'd say it's unlikely for new languages will be added until beginning of May.

However, this shouldn't stop you from adding sentences and translations in Kabyle. If you are contributing only in Kabyle, we can easily update the language of your sentences from Berber to Kabyle, once Kabyle is effectively added.

Thanks for your understanding.

**Closed by trang** 2018-03-04 17:11 UTC

**Comment by vujma** [comment] 2018-03-04 17:25
Ok i got your point.
There is no problem from my side, i will continue the translations and audio recording.
Yes i only translate from french and english into Kabyle.

**Comment by RyckRichards** [comment] 2018-03-04 19:36
Related: #1530 and #1531

**Comment by ckjpn** [comment] 2018-03-05 03:01
TRANG, 

How will this affect all the audio he has contributed?
Will you be easily able to transfer all the audio files designated as "ber" to "kab"?
