### ISSUE TITLE
A deleted sentence didn't actually get deleted

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#862] opened 2015-10-23 23:43 UTC
Bug - a deleted sentence didn't actually get deleted
(Perhaps there are others, so someone should check, I think.)

https://tatoeba.org/eng/sentences/show/1002809

See the logs on the right side of the page.
![screen shot 2015-10-24 at 08 42 06](https://cloud.githubusercontent.com/assets/7934273/10707284/27bb1562-7a2b-11e5-9cf5-ee4f7653dc13.png)

**Comment by trang** [comment] 2016-03-18 10:47
Duplicate of #699.

**Closed by trang** 2016-03-18 10:47 UTC
Labels: bug
