### ISSUE TITLE
Sentences Dataset has missing lang codes

### ISSUE THREAD

**Issue by loretoparisi** [Tatoeba/tatoeba2#2128] opened 2020-02-05 16:15 UTC
Hello, the [last](https://tatoeba.org/ita/downloads) available release of the sentences dataset, seems to have missing lang codes like:

```
$ cat sentences.csv | grep "Pumupunta si Tom sa bahay ng mga magulang nya "
7091736		Pumupunta si Tom sa bahay ng mga magulang nya tuwing sabado at linggo
```

**Comment by jiru** [comment] 2020-02-06 08:46
Hello Loreto and welcome here. :-) Thank you for reporting this problem to us.

This sentence belongs to the ["unknown language" part of the corpus](https://tatoeba.org/eng/Sentences/show_all_in/unknown/none). These are sentences of which don’t know the language, or that belong to a language that has an ISO code that is not yet supported by Tatoeba.

That said, the language should show as "\N" in the CSV export, not an empty string. Is that the problem you are pointing out?

**Comment by loretoparisi** [comment] 2020-02-06 14:17
@jiru thank you, in fact we have noticed that there were `\N` as well, but not always were there are the empty ISO codes.

**Comment by AndiPersti** [comment] 2020-02-06 16:58
There was a bug when editing a sentence in an unknown language which stored the language as an empty string instead of `\N` (i.e. `NULL`) in the database. The fix was [merged just a few days ago](https://github.com/Tatoeba/tatoeba2/pull/2070), so older defects caused by this bug are still present in the database.

I've noticed this problem myself a few weeks ago where there were 3 such sentences in the export but currently there are 6:

    7091736         Pumupunta si Tom sa bahay ng mga magulang nya tuwing sabado at linggo   Manukavina      2018-08-26 01:25:42     2019-08-03 07:19:33
    7663935         今天天氣真他媽的熱      DeanFumu        2018-12-26 02:30:21     2018-12-26 02:31:26
    7750241         ჭარილს ჭარუნს.  SadeceTurkce    2019-01-25 03:39:40     2019-01-25 03:43:56
    8363285         옆으로 비켜.    Eunhee  2019-12-04 04:46:49     2019-12-04 04:47:10
    8446230         Ttxil-k, sseɣsi asawal-nnek.    Amastan 2020-01-12 18:50:24     2020-01-12 18:50:33
    8482206         Tilbereptur Ali ey uşşak, ol idi gerçi burna akılıngız. soliloquist     2020-01-22 23:52:06     2020-01-23 23:13:02

[7091736](https://tatoeba.org/deu/sentences/show/7091736): A comment says this isn't Tagalog but the sentence was changed afterwards. Google Translate detects it as Filipino but that [seems to be a political difference](https://en.wikipedia.org/wiki/Filipino_language#Filipino_vs._Tagalog). I've asked the sentence owner Manukavina for clarification.

[7663935](https://tatoeba.org/deu/sentences/show/7663935): It looks like there was a problem while editing that sentence because the original text was `Today is so fucking hot.` and it is linked to the Chinese sentence [7663934](https://tatoeba.org/deu/sentences/show/7663934) with the same text.

[7750241](https://tatoeba.org/deu/sentences/show/7750241): Already shown as Mingrelian but that language was added [just one day after the export](https://github.com/Tatoeba/tatoeba2/milestone/203?closed=1) so this should be fixed with the next export.

[8446230](https://tatoeba.org/eng/sentences/show/8446230): Looks like a problem while adding (original text was `*`). Looks like a Berber sentence. I've just asked Amastan in the comments.


[8363285](https://tatoeba.org/deu/sentences/show/8363285): Looks like a problem while editing. The language of the original text was Korean and Google Translate says the current text is also Korean.
    
    $ grep '   8363285 ' contributions.csv
    Eunhee  2019-12-04 04:46:49     insert  sentence        8363285 kor     \N      비켜.
    Eunhee  2019-12-04 04:46:49     insert  license 8363285 kor     \N      CC BY 2.0 FR
    Eunhee  2019-12-04 04:46:49     insert  link    40051   \N      8363285
    Eunhee  2019-12-04 04:46:49     insert  link    8363285 kor     40051
    Eunhee  2019-12-04 04:47:10     update  sentence        8363285 \N      \N      옆으로 비켜.


[8482206](https://tatoeba.org/eng/sentences/show/8482206): Already shown as Chagatai but that language was added [just one day after the export](https://github.com/Tatoeba/tatoeba2/milestone/203?closed=1) so this should be fixed with the next export.

**Comment by jiru** [comment] 2020-02-07 03:11
Thank you for reviewing this, Andreas. Let's wait and see for the next CSV export. It will appear this Saturday.

**Comment by jiru** [comment] 2020-02-23 08:22
Sorry for the delay, I checked the latest sentences.csv export and only sentence 7663935 is missing the language code. I manually fixed the language of that sentence in the database (but that sentence has been proposed for deletion anyway). The next export on the 1st of March should be free of missing language codes.

**Comment by jiru** [comment] 2020-03-01 15:49
The latest sentences.csv file is now free from empty language codes. Thanks again @loretoparisi for reporting the problem to us!

**Closed by jiru** 2020-03-01 15:49 UTC
