### ISSUE TITLE
On /vocabulary/add_sentences/, sentence counts are incorrect.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1388] opened 2016-12-29 23:44 UTC
## The Problem

Reported on the Wall by Zumley

... on the 'Vocabulary that needs sentences' pages, vocabulary items are incorrectly displaying their amount of sentences.

https://tatoeba.org/eng/wall/index#message_27832

## Screenshot
https://tatoeba.org/eng/vocabulary/add_sentences/eng/page:7
https://tatoeba.org/eng/sentences/search?query=%3D%22apparel%22&from=eng
https://tatoeba.org/eng/sentences/show/5498345
![screen_shot_2016_12_30_at_08_17_18](https://cloud.githubusercontent.com/assets/7934273/21557206/2ba69e6c-ce6c-11e6-82b6-f137e9efca01.png)

**Comment by trang** [comment] 2018-08-26 00:43
I cannot reproduce this anymore. Closing.

**Closed by trang** 2018-08-26 00:43 UTC
Labels: bug
