### ISSUE TITLE
The counts of sentences with a given tag in the autocompletion don't match the counts in the dedicated tag's page

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#2649] opened 2021-03-13 22:19 UTC
**To Reproduce**
1. Go to a sentence page
2. Type a tag
3. Watch the count of sentences containing that tag in the autocompletion
4. Add the tag
5. Go to the page containing that tag
6. Select the option to see sentences in all the languages
7. Check the total number of sentences with that tag to see the difference

**Expected behavior**
The total number of the sentences containing a given tag should be the same everywhere.

**Comment by jiru** [comment] 2021-03-14 12:49
I cannot reproduce this issue. Note that the number between step 3 and step 7 is supposed to be different (increased by one) because you tag one sentence in step 4. Just to be sure, what’s the tag you are adding?

**Comment by Guybrush88** [comment] 2021-03-14 13:04
I saw this behavior with the tags "presente" and "passato prossimo".

I forgot to add, as a link in point 7, such pages: https://tatoeba.org/ita/tags/show_sentences_with_tag/5616

The number from this link is different from the number in the autocompletion, from what I saw

**Comment by Guybrush88** [comment] 2021-03-14 13:16
I just got a screenshot about the autocompletion
![Istantanea_2021-03-14_14-13-55](https://user-images.githubusercontent.com/1702194/111069927-a833dd00-84cf-11eb-85de-6e10066893bb.png)

The autocompletion says that there are 63.570 sentences with that tag, while this page: https://tatoeba.org/ita/tags/show_sentences_with_tag/5616 says that there are 63.586

**Comment by jiru** [comment] 2021-03-14 16:30
The count in the autocompletion box is the same as the count in the "browse by tags" page. I will close this as a duplicate of #1622.

**Closed by jiru** 2021-03-14 16:30 UTC
Labels: bug

**Comment by Guybrush88** [comment] 2021-03-14 17:59
sorry, my bad, I wasn't aware of that
