### ISSUE TITLE
"annexe_content" shows dates not localized

### ISSUE THREAD

**Issue by lagleki** [Tatoeba/tatoeba2#622] opened 2015-03-23 16:45 UTC
{date} used e.g. in string #922 in Transifex is a mergefield of a date in English. It should be localizable.

E.g. open http://dev.tatoeba.org/spa/wall/index and see "annexe_content" module:

Feb 19th 2015, 09:26, by CK
Feb 17th 2015, 09:18, by TRANG
Feb 13th 2015, 08:02, by CK
Feb 2nd 2015, 18:05, by gillux

**Comment by trang** [comment] 2015-03-23 20:09
I'm closing this, it's a duplicate of #152.

**Closed by trang** 2015-03-23 20:09 UTC
