### ISSUE TITLE
The furigana interferes with copying the main Japanese sentence.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1077] opened 2016-03-25 05:24 UTC
https://tatoeba.org/sentences/show/5006900

![screen shot 2016-03-25 at 19 02 41](https://cloud.githubusercontent.com/assets/7934273/14042329/3ecbda02-f2bc-11e5-8348-843aaf52d250.png)

**Comment by ckjpn** [comment] 2016-03-25 05:32
Actually, it can be copied, if you click the "kana" icon first.
I guess it's just unexpected behavior, not a bug.

I'll delete this.

**Comment by trang** [comment] 2016-03-25 10:00
@ckjpn simply close the issue when you change your mind and think it's not valid. No need to erase the whole content.

In this case, I think it was a valid issue. Unexpected behavior are bugs.

**Comment by ckjpn** [comment] 2016-03-25 10:24
I think that this only happens if the furigana has been manually edited.

https://tatoeba.org/eng/sentences/show_all_in/jpn/und/none/indifferent

![screen shot 2016-03-25 at 19 22 39](https://cloud.githubusercontent.com/assets/7934273/14042635/1c42cbe6-f2bf-11e5-939d-4247a7a79376.png)

**Comment by ckjpn** [comment] 2016-03-25 10:35
I solved the problem for myself with the following CSS in Stylish.
Of course, this isn't what most people will want.

/* hide furigana */
rt{display:none;}

**Comment by dispyfree** [comment] 2016-05-04 18:26
I suggest just disabling copying for the transcription rather than not displaying the transcription.
Currently the transcription cannot be copied without garbling it up anyway. 

rp, rt {
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
 user-select: none;
}


(http://stackoverflow.com/a/16926913)

**Comment by trang** [comment] 2016-05-05 00:47
I was going to say I can't reproduce this, but it seems it's because I was using Firefox. In Firefox (version 45) on Windows, the furigana isn't copied. On Chrome (version 50) however, it is copied.

I tried quickly the `user-select: none`, it doesn't seem to have any effect on copying. It only makes it look like you're not selecting the furigana, but it still copies it.

**Comment by jiru** [comment] 2016-12-03 14:48
I think this issue can be closed now we have the copy-to-clipboard button.

**Comment by ckjpn** [comment] 2016-12-03 17:09
> copy-to-clipboard button

I don't see any such button.  Am I missing something?

![screen shot 2016-12-04 at 02 08 59](https://cloud.githubusercontent.com/assets/7934273/20860913/ab3799a2-b9c6-11e6-9791-89017c796cb4.png)
![screen shot 2016-12-04 at 02 08 48](https://cloud.githubusercontent.com/assets/7934273/20860914/ab3a3464-b9c6-11e6-801d-ee1f122bcaae.png)


URL: 
https://tatoeba.org/eng/sentences/search?query=&from=jpn&to=eng&has_audio=yes&trans_filter=exclude&trans_to=eng&sort=random

**Comment by jiru** [comment] 2016-12-03 18:40
Right. The copy-to-clipboard button still needs to be activated in the profile.

**Closed** 2018-06-25 20:30 UTC
Labels: bug
