### ISSUE TITLE
Allow admins to set the correctness of all of a user's sentences to a value via the GUI

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#937] opened 2015-11-27 16:42 UTC
Sometimes, users post large numbers of incorrect sentences, or copyrighted ones, and fail to respond to comments asking them to change their behavior and to fix the existing sentences. In these cases, we need not only to set an indicator at the user level, but also to have a quick way to mark all of the user's sentences as untrusted so that other users won't translate them. It is possible for admins to change the "correctness value" of a sentence via the GUI, but this is impractical for large numbers of sentences. It is also possible for admins with database access to do this with an SQL command, but the number of admins who have this access is small, and they do not always have access to a machine from which they can perform these commands.

**Comment by AndiPersti** [comment] 2020-12-25 05:04
@alanfgh We [recently added](https://github.com/Tatoeba/tatoeba2/pull/2591) a button to a suspended/blocked user's sentences page to mark all sentences as unreliable.

Does this solve this issue?

**Comment by trang** [comment] 2020-12-27 11:01
Thanks for spotting this @AndiPersti, I think we can safely close this issue :) #2586 is pretty much a duplicate of this one. 

This issue is also quite old. If there's anything else that needs to be done, it is better to open a fresh new issue.

**Closed by trang** 2020-12-27 11:01 UTC
Labels: enhancement

**Comment by alanfgh** [comment] 2020-12-27 16:57
@AndiPersti Yes, it does solve the issue. Thank you!
