### ISSUE TITLE
"Browse by language" page is inconsitent with the other "Browse by" pages

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2157] opened 2020-02-21 22:38 UTC
Looking that the "Browse" menu:
- The page "Browse by list" shows the list of lists. Selecting a list displays the sentences in that list.
- The page "Browse by tags" shows the list of tags. Selecting a tag displays the sentences with that tag.
- The page "Browse by language" shows directly a list of sentences in a somewhat arbitrary language (for the first time you visit the page).

If we were to be consistent, "Browse by languages" should display the list of languages. Then selecting a language displays sentences in that language.

The most simple change we can do is to use the "[Number of sentences per language](https://tatoeba.org/eng/stats/sentences_by_language)" for "Browse by language".

- The URL could be changed to `/languages/index`.
- The title could indicate the number of supported languages instead of the total number of sentences.
- The "Number of sentences with audio by language" could be removed. Those stats are already displayed in the "Browse audio" page.

Later on we can improve the page with more information about each language.

**Comment by agrodet** [comment] 2020-03-23 03:08
> The title could indicate the number of supported languages instead of the total number of sentences.

The title could indicate both. "8 498 843 sentences in 358 languages" gives more useful information and (, more important from my view :P), makes sense both as a title for the "Browse by language" and the link from the Stats Block.

If you allow me to draw on the "consistency" issue, I wonder if the [Browse audio](https://tatoeba.org/eng/audio/index) page is useful as it is. I don't mean that browsing all languages is useless, actually it can be fun to hear languages we don't understand (although English is overwhelming).
I wonder if the best landing page when a user click on "Browse audio" is simply not the same as the one you mention (after thinking longer about it, no, it's not). On the current stats page, we have both sentences in languages and audio. To me, the title in the audio column `Number of sentences with audio by language` should be replaced by `{totalAudio} sentences with audio` or `{totalAudio} sentences have audio in {totalLang} languages`. That way, the title would give useful information, while it is currently just a plain column title.  
Then, the `Browse audio for all languages` link, at the bottom of the column, should send to the current `audio/index`. However, the page would give more insight if the sentences were displayed randomly or if both `random` and `last added` orders were available (default to random is the best for this page in my opinion).  

Now, I realize that I spoke mainly of the "Browse audio" while the title of the issue is about the "Browse by language". Excuse my bad manners, but since you mentioned the stats page, I think it's a good idea to improve this page at the same time. To summarize my points: 

- The title of future `languages/index` would give more information if it was "8 498 843 sentences in 358 languages"
- On that same page the title of the audio column would give more information it it was something in the taste of `{totalAudio} sentences with audio` or `{totalAudio} sentences have audio in {totalLang} languages`
- The `audio/index` page should be displayed in random by default, with the option to display it by `Last added` (ascending / descending, the usual sort criterion we have on other pages)
- If the page is modified according to the point above (or similar), I think it makes sense for `audio/index` to be the landing page of "Browse audio"

**Comment by ckjpn** [comment] 2020-09-04 00:43
This looks good.  It seems intuitive and is attractive.
https://dev.tatoeba.org/eng/sentences/index

Perhaps the same thing could be done for "browse by audio."

## On "ALL LANGUAGES" ....

This seems strange to me.
"1+ sentence"

Perhaps the last one could be "Fewer than 10 sentences" of use the less than sign <.
Or "1 or more sentences".

Note that all languages are actually part of the category at the bottom, currently called "1+ sentence". 
So, logically, if these titles are going to be used, then the order should be reversed, so that all languages are listed under "1+ sentence," and then all languages with 10 or more sentences fall under the next category.

### An Idea that might solve this problem.

The dividing line titles could be like this.

Between 10,001 and 100,000 Sentences

Between 1,001 and 10,000 Sentences

Fewer than 10 Sentences


### A minor point

Perhaps all caps for the choices at the top of the page could be removed.
It is usually slower to read all caps, especially when the font is smaller, so text that is not all caps is easier on the eyes and seems friendlier.  You could use a bold font if you feel this needs to stand out a bit.


### AlanF_US's comment on the Wall

 _I particularly like the display of languages by number of sentences (100,000+, 10,000+, etc.). That might be especially helpful in motivating people to add sentences in order to move their language from one group to another (for instance, another 3,000+ sentences will get Polish into the 100,000+ group)._

#### Perhaps for motivational purposes, more increments would help for all languages with over 10,000 sentences.


Between 150,001 and 200,000 Sentences
Between 100,001 and 150,000 Sentences
Between 50,001 and 100,000 Sentences
Between 10,001 and 50,000 Sentences

The increments wouldn't necessarily all need to be equal, especially near the top with few languages.

Between 300,001 and 700,000 Sentences
Between 200,001 and 300,000 Sentences

**Comment by jiru** [comment] 2020-09-04 23:23
>  Perhaps the same thing could be done for "browse by audio."

Definitely.

> This seems strange to me.
> "1+ sentence"
> 
> Perhaps the last one could be "Fewer than 10 sentences" of use the less than sign <.
> Or "1 or more sentences".

You have a point.

> Note that all languages are actually part of the category at the bottom, currently called "1+ sentence".
> So, logically, if these titles are going to be used, then the order should be reversed, so that all languages are listed under "1+ sentence," and then all languages with 10 or more sentences fall under the next category.

Even though pretty much all languages fall under the "1+ sentence" category, it doesn’t mean we have to nest every other category inside it. I believe the information is intuitive enough like this. Unless UX tests show that users are having trouble understanding the page, I don’t think there is a problem.

> Perhaps for motivational purposes, more increments would help for all languages with over 10,000 sentences.

While it’s technically easy to change the thresholds, I’m afraid this may bring more trouble than benefit. To begin with, who is going to decide on the thresholds and maintain them over time? Not me. I am also afraid that making them look like "decided by somebody" would be source of arguing about which threshold we should use, people asking for extra thresholds etc. I think it’s safer (and visually cleaner) to keep them as consistent and simple as possible.

**Comment by AndiPersti** [comment] 2020-09-14 07:34
Closed via #2294.

**Closed by AndiPersti** 2020-09-14 07:34 UTC
Labels: enhancement

**Comment by ckjpn** [comment] 2020-09-14 08:04
One thing I noticed it now the default is /none and before it was /und (or perhaps the last setting used and stored in a cookie).

https://tatoeba.org/eng/sentences/show_all_in/eng/none

It would be nice if one didn't have to load the page as /none and then reload the page as /und each time.

**Comment by jiru** [comment] 2020-09-20 21:14
The default used to be "none". I confirm that I removed the remembering mechanism for that drop down.
