### ISSUE TITLE
Search limited to a tag reports a different count than the tags page

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1331] opened 2016-10-08 15:50 UTC
## The Problem

When doing an advanced search limited to a tag, it appears that not all tagged sentences are being searched.
## Screenshot

This had the search results, with part of the "Browse Tags" page pasted on top of that image.

![screen shot 2016-10-09 at 00 41 56](https://cloud.githubusercontent.com/assets/7934273/19214289/3c9098e2-8dba-11e6-86bf-8c3dc5088497.png)
## URLs

The Search:
https://tatoeba.org/eng/sentences/search?query=&from=und&to=und&orphans=no&unapproved=no&user=&tags=List+907&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=created
The Tags URL:
https://tatoeba.org/eng/tags/view_all
## Note

I suspect that all sentences are being searched, but that the number in the search results is perhaps wrong.

One of the recently contributed and tagged sentences does show up with this search.

https://tatoeba.org/eng/sentences/search?query=I+didn%27t+read+the+message.&from=eng&tags=List+907&has_audio=&sort=random&to=und&trans_filter=limit&trans_to=und&trans_link=direct&trans_has_audio=

**Comment by ckjpn** [comment] 2016-10-10 00:11
## Additional Clarification

The results for tagged "list 907" should have more occurrences than for "with audio."

### Tagged "List 907," not yet in Japanese, random results
Advanced search (1000 results out of 147465 occurrences)

https://tatoeba.org/eng/sentences/search?query=&from=eng&to=jpn&orphans=no&unapproved=no&user=&tags=List+907&has_audio=&trans_filter=exclude&trans_to=jpn&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random

### With Audio, not yet in Japanese, random results
Advanced search (1000 results out of 202271 occurrences)

https://tatoeba.org/eng/sentences/search?query=&from=eng&to=jpn&orphans=no&unapproved=no&user=&tags=List+907&has_audio=&trans_filter=exclude&trans_to=jpn&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random

### Note
Almost all of the 200,000+ "with audio" English sentences are tagged "list 907".  There are 400,000+ sentences tagged "list 907."

**Comment by jiru** [comment] 2018-06-04 14:15
So there are two problems involved in the count difference. The number in the search result looks actually quite accurate, while the one reported on the [tags page](https://tatoeba.org/tags/view_all) is incorrect. I found two problems regarding the count in the tags page:
1. The SQL request needs a UNIQ or DISTINCT somewhere because it’s counting duplicates. This accounts for the majority of the difference.
2. It’s counting a certain number of removed sentences.

I found a total of 113 sentences included in the count of tags pages but not included in the search result:
[806845](https://tatoeba.org/sentences/show/806845),[2908807](https://tatoeba.org/sentences/show/2908807),[2955974](https://tatoeba.org/sentences/show/2955974),[2956135](https://tatoeba.org/sentences/show/2956135),[3092545](https://tatoeba.org/sentences/show/3092545),[3213726](https://tatoeba.org/sentences/show/3213726),[3377072](https://tatoeba.org/sentences/show/3377072),[3417532](https://tatoeba.org/sentences/show/3417532),[3728525](https://tatoeba.org/sentences/show/3728525),[3728970](https://tatoeba.org/sentences/show/3728970),[3734821](https://tatoeba.org/sentences/show/3734821),[3738381](https://tatoeba.org/sentences/show/3738381),[3825166](https://tatoeba.org/sentences/show/3825166),[3922211](https://tatoeba.org/sentences/show/3922211),[4014554](https://tatoeba.org/sentences/show/4014554),[4496013](https://tatoeba.org/sentences/show/4496013),[4563638](https://tatoeba.org/sentences/show/4563638),[4703093](https://tatoeba.org/sentences/show/4703093),[4811437](https://tatoeba.org/sentences/show/4811437),[4853269](https://tatoeba.org/sentences/show/4853269),[4890449](https://tatoeba.org/sentences/show/4890449),[4956757](https://tatoeba.org/sentences/show/4956757),[4998387](https://tatoeba.org/sentences/show/4998387),[5006756](https://tatoeba.org/sentences/show/5006756),[5008766](https://tatoeba.org/sentences/show/5008766),[5008767](https://tatoeba.org/sentences/show/5008767),[5008768](https://tatoeba.org/sentences/show/5008768),[5008769](https://tatoeba.org/sentences/show/5008769),[5008771](https://tatoeba.org/sentences/show/5008771),[5008772](https://tatoeba.org/sentences/show/5008772),[5008773](https://tatoeba.org/sentences/show/5008773),[5032969](https://tatoeba.org/sentences/show/5032969),[5098340](https://tatoeba.org/sentences/show/5098340),[5098345](https://tatoeba.org/sentences/show/5098345),[5103508](https://tatoeba.org/sentences/show/5103508),[5112795](https://tatoeba.org/sentences/show/5112795),[5112797](https://tatoeba.org/sentences/show/5112797),[5112799](https://tatoeba.org/sentences/show/5112799),[5112800](https://tatoeba.org/sentences/show/5112800),[5112804](https://tatoeba.org/sentences/show/5112804),[5112836](https://tatoeba.org/sentences/show/5112836),[5112837](https://tatoeba.org/sentences/show/5112837),[5112839](https://tatoeba.org/sentences/show/5112839),[5132213](https://tatoeba.org/sentences/show/5132213),[5149979](https://tatoeba.org/sentences/show/5149979),[5155168](https://tatoeba.org/sentences/show/5155168),[5157779](https://tatoeba.org/sentences/show/5157779),[5158664](https://tatoeba.org/sentences/show/5158664),[5162567](https://tatoeba.org/sentences/show/5162567),[5163864](https://tatoeba.org/sentences/show/5163864),[5163868](https://tatoeba.org/sentences/show/5163868),[5166550](https://tatoeba.org/sentences/show/5166550),[5173882](https://tatoeba.org/sentences/show/5173882),[5183296](https://tatoeba.org/sentences/show/5183296),[5183306](https://tatoeba.org/sentences/show/5183306),[5183309](https://tatoeba.org/sentences/show/5183309),[5187084](https://tatoeba.org/sentences/show/5187084),[5187087](https://tatoeba.org/sentences/show/5187087),[5187471](https://tatoeba.org/sentences/show/5187471),[5189297](https://tatoeba.org/sentences/show/5189297),[5190906](https://tatoeba.org/sentences/show/5190906),[5191980](https://tatoeba.org/sentences/show/5191980),[5211684](https://tatoeba.org/sentences/show/5211684),[5213791](https://tatoeba.org/sentences/show/5213791),[5213797](https://tatoeba.org/sentences/show/5213797),[5213829](https://tatoeba.org/sentences/show/5213829),[5220164](https://tatoeba.org/sentences/show/5220164),[5221347](https://tatoeba.org/sentences/show/5221347),[5223714](https://tatoeba.org/sentences/show/5223714),[5223715](https://tatoeba.org/sentences/show/5223715),[5241602](https://tatoeba.org/sentences/show/5241602),[5241608](https://tatoeba.org/sentences/show/5241608),[5241622](https://tatoeba.org/sentences/show/5241622),[5257732](https://tatoeba.org/sentences/show/5257732),[5257734](https://tatoeba.org/sentences/show/5257734),[5257737](https://tatoeba.org/sentences/show/5257737),[5260874](https://tatoeba.org/sentences/show/5260874),[5270058](https://tatoeba.org/sentences/show/5270058),[5272716](https://tatoeba.org/sentences/show/5272716),[5272739](https://tatoeba.org/sentences/show/5272739),[5274067](https://tatoeba.org/sentences/show/5274067),[5280508](https://tatoeba.org/sentences/show/5280508),[5283872](https://tatoeba.org/sentences/show/5283872),[5294566](https://tatoeba.org/sentences/show/5294566),[5298444](https://tatoeba.org/sentences/show/5298444),[5300590](https://tatoeba.org/sentences/show/5300590),[5306657](https://tatoeba.org/sentences/show/5306657),[5306658](https://tatoeba.org/sentences/show/5306658),[5306666](https://tatoeba.org/sentences/show/5306666),[5350329](https://tatoeba.org/sentences/show/5350329),[5350331](https://tatoeba.org/sentences/show/5350331),[5448798](https://tatoeba.org/sentences/show/5448798),[5506536](https://tatoeba.org/sentences/show/5506536),[5515321](https://tatoeba.org/sentences/show/5515321),[5525674](https://tatoeba.org/sentences/show/5525674),[5549674](https://tatoeba.org/sentences/show/5549674),[5577221](https://tatoeba.org/sentences/show/5577221),[5745110](https://tatoeba.org/sentences/show/5745110),[5745112](https://tatoeba.org/sentences/show/5745112),[5747212](https://tatoeba.org/sentences/show/5747212),[5805212](https://tatoeba.org/sentences/show/5805212),[5805445](https://tatoeba.org/sentences/show/5805445),[5805479](https://tatoeba.org/sentences/show/5805479),[5838838](https://tatoeba.org/sentences/show/5838838),[5844792](https://tatoeba.org/sentences/show/5844792),[5849987](https://tatoeba.org/sentences/show/5849987),[5856442](https://tatoeba.org/sentences/show/5856442),[5856451](https://tatoeba.org/sentences/show/5856451),[5859341](https://tatoeba.org/sentences/show/5859341),[6921315](https://tatoeba.org/sentences/show/6921315),[6927360](https://tatoeba.org/sentences/show/6927360),[6927485](https://tatoeba.org/sentences/show/6927485),[6927486](https://tatoeba.org/sentences/show/6927486)

**Comment by jiru** [comment] 2018-06-12 10:45
> 1. The SQL request needs a UNIQ or DISTINCT somewhere because it’s counting duplicates. This accounts for the majority of the difference.

To elaborate on this, the problem is that we’re having duplicate tags in our database. There are two kinds:
1. Some are the result of the deduplication script, when two sentences having the same tag are merged. Example: sentence 19549. In #514, we took care of the showing the tag list correctly on the sentence page regardless of duplicates, but they are still in the database messing up with the counting.
```sql
> SELECT * FROM tags_sentences WHERE tag_id = 407 AND sentence_id = 19549;
+--------+--------+---------+-------------+---------------------+
| id     | tag_id | user_id | sentence_id | added_time          |
+--------+--------+---------+-------------+---------------------+
|   1286 |    407 |    1396 |       19549 | 2010-06-16 03:40:20 |
| 225913 |    407 |    8099 |       19549 | 2012-01-20 17:47:28 |
+--------+--------+---------+-------------+---------------------+
```
2. Some are "real" duplicates: the same user put the same tag on the same sentence twice. I’m not sure how that happened. Example: sentence 16113.
```sql
> SELECT * FROM tags_sentences WHERE tag_id = 7770 AND sentence_id = 16113;
+---------+--------+---------+-------------+---------------------+
| id      | tag_id | user_id | sentence_id | added_time          |
+---------+--------+---------+-------------+---------------------+
| 1118694 |   7770 |    1396 |       16113 | 2016-09-25 00:17:15 |
| 1772146 |   7770 |    1396 |       16113 | 2018-02-23 00:11:40 |
+---------+--------+---------+-------------+---------------------+
```

**Comment by jiru** [comment] 2018-06-18 23:10
I think I fixed most of the count difference, which was caused by duplicate tags.

There are also some invalid references to deleted sentences in the table `tags_sentences`. But I don’t know how they got there, I can’t reproduce what caused this, so I think we can close this bug until someone finds a specific scenario that messes up the counting.

@trang You can delete these invalid references using the following query:
```sql
delete from tags_sentences where id in (
  select tsid from (
    select ts.id as tsid from tags_sentences ts
    left join sentences s on s.id = ts.sentence_id
    where s.id is null
  ) as c
);
```
After running that query, reinstall the SQL procedure clean_up_tag_sentence_count() and execute it.

**Comment by trang** [comment] 2018-06-25 00:20
Seems good. Closing.

Just a note: the search excludes by default orphan sentences and unapproved sentences. I was a bit confused at first because the numbers were slightly off, between the search results and the tags page. Then I remember I should to select "Is orphan" = "Any" and "Is unapproved" = "Any".

**Closed by trang** 2018-06-25 00:20 UTC
Labels: bug
