### ISSUE TITLE
tatoeba.org VS. dev.tatoeba.org

### ISSUE THREAD

**Issue by mramosch** [Tatoeba/tatoeba2#2643] opened 2021-03-11 16:26 UTC
When loading the very same sentence (from the very same search result) on the dev-server, the response is a little bit faster as the response of the production-server, I guess that’s due to the smaller database-size of the outdated data set on the dev-server. Small difference, no problem at all...

However, the response data from the production-server seems to come in different chunks than the ones from the dev-server.

The dev-server keeps the UI (e.g. the black Tatoeba top bar including all writing etc.) of the search-results page untouched because it’s the equivalent layout than the one on the currently loading sentence-page. Only the differing parts get refreshed, the rest stays in place without any flickering.

On the production-server, however, the transition from the search-result page to the sentence page (upon selection of a sentence) is sluggish and one can see, that nothing is used out of the cache, everything seems to somehow get reloaded and redrawn on screen, even the same bits and parts that are already on screen from the search-results page.

On the dev-server the whole page appears to be updated in one pass of screen refresh, on the production server it is a 3 passes refreshing.

Even when loading the same sentence page from within code, where I can load the html into the browser window after getting the callback for a successful response from the server, I can log events to the console and it is clearly visible, that the logs come in one shot when dealing with the dev-server as opposed to the logs trickling in  step-by-step when the response comes from the production server.

We are talking about ~1 second difference here...

**Comment by mramosch** [comment] 2021-03-11 19:15
After doing some more testing I can confirm that reloading the very same sentence from  the dev-server doesn’t show any refresh flickering at all unless you scroll the  page a little bit. But even then it looks like the page is just repositioned to the top in its entirety, no signs of an incremental buildup of the different parts of the page.

Reloading the very same page from the production-server over and over again rebuilds the page in 3 steps over a duration of about 500ms for each load.

The very first load of the page on the dev-server is snappy and almost shows up as one uniform block on the screen, on the production-server however, the first load takes about 1.5 seconds for the three steps/blocks to appear...

**Comment by jiru** [comment] 2021-03-13 18:27
I cannot reproduce this issue. I assume you are using Safari. Could you try with a different browser or device to see if it makes a difference?

**Comment by mramosch** [comment] 2021-03-13 18:50
To demonstrate it visually:

This is a Safari web-view in code and I am loading the same 3 sentences (result 2, result 3, result 2) from the same search result from tatoeba.org (video clip 1) and then from dev.tatoeba.org (video clip 2).

100% the same code, only the URL is changed (hardcoded).

You get the very same behavior in the Safari-App, however in code you can see the delay better because of the different loading stages of the AngularJS and DOM code...



https://user-images.githubusercontent.com/725445/111040440-38701480-8433-11eb-8142-89760cc29b70.mov



https://user-images.githubusercontent.com/725445/111040622-15923000-8434-11eb-9e4a-cf637cee0f44.mov

**Comment by jiru** [comment] 2021-03-14 12:11
Thank you for the videos. It looks like you are using some client-side customization around the sentence block. Could you try again without the customization to see if it makes a difference? (Try to deactivate any addon, plugin, extension etc.).

In addition, could you try with a different browser or device to see if it makes a difference?

**Comment by mramosch** [comment] 2021-03-14 12:57
Video of the Original Safari-App without any client-side interference whatsoever!

Switching back and forth between tat and dev.tat server, URL entered manually in the browser’s address field...

Did this about 10 times before so any cache should be warmed up and give no disadvantage/advantage to either server.

You can clearly see the difference between the page-loading behavior, which only gets magnified when doing client-side customization. What you see on the other videos (when the text of the additional menu or the multiple-choice facility in the source sentence get their orange colors applied) is done onload() of <body>. Here the delay is visible the most.

So something seems to come delayed from the tat server and hence delay the execution of page load and subsequently the DOM onload initialization. On the dev.tat server everything works like a greased lightning.

And as I said before, reloading the very same sentence page on the tat server rebuilds the whole page every time as where on the dev.tat server you can’t see the slightest flicker on refresh, unless you scroll the page position a bit, then you’ll see the page repositioning itself back to the top. But in one block, without visible incremental build-ups...

I have pretty much constant time for all scenarios, independent from day-time, so different behavior of the two server seems unaffected by bottlenecks in the internet connection or any client-side customization.

The very same code is running, only the URL is changed from tat to dev.tat...



https://user-images.githubusercontent.com/725445/111068663-fe9e1d00-84c9-11eb-8b7c-c1992bb49196.mp4

**Comment by jiru** [comment] 2021-03-14 16:51
I don’t really know since I cannot reproduce this issue. This only difference I can think of is that tatoeba.org includes an additional Javascript block for Google Analytics.

Besides, could you try with a different browser or device to see if it makes a difference?

**Comment by jiru** [comment] 2021-03-14 16:57
Could you also try as a guest (after logging out)?

**Comment by mramosch** [comment] 2021-03-14 18:12
You’re a genius ;-)

For some reason I have deactivated my GoogleAnalytics-Killer and didn’t realize, that on dev.tat.org there is no GA-script in the HTML but there is on tat.org!

No that I switched on the GA-Killer again, everything is lightning fast just like on the dev server!

That is very good news!

Thanks again ;-)


———

**Comment by jiru** [comment] 2021-03-14 19:38
Well, if you are fine with this I will close this issue then. :slightly_smiling_face:

**Closed by jiru** 2021-03-14 19:38 UTC
Labels: optimization

**Comment by mramosch** [comment] 2021-03-14 19:59
Perfect!
