### ISSUE TITLE
Reversing the sort of sentences with ratings would be more useful.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1052] opened 2016-03-09 01:35 UTC
Instead of the current sort, which shows the lowest-numbered sentences first, show the highest-numbered sentences first.

At least for me, I add "OK" ratings to new sentences as they come in, so it would be more useful to see what's been newly rated, rather than see the same old sentences each time the following URL is accessed.

https://tatoeba.org/eng/collections/of/CK

PS. I still think it would be a good idea to call these ratings "ratings" rather than "collections."

**Comment by sacredceltic** [comment] 2016-03-09 08:03
>I still think it would be a good idea to call these ratings "ratings" rather than "collections."

I think what you're missing is that it IS a rating system, but one that is ashamed of itself, so it goes in hiding...

**Comment by trang** [comment] 2016-03-12 20:29
Duplicate of #756.

**Closed by trang** 2016-03-12 20:29 UTC
Labels: enhancement
