### ISSUE TITLE
iPad layout looks wrong - Likely iPhones, too.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1009] opened 2016-02-19 16:03 UTC
Note the the layout isn't quite what is expected.
(Also, the audio doesn't play)

![ipod_layout_error](https://cloud.githubusercontent.com/assets/7934273/13180856/8e18eb1e-d76d-11e5-940b-ac656a41ec21.png)

This search: https://tatoeba.org/eng/sentences/search?query=%22%E3%81%A7%E3%81%97%E3%81%9F%E3%80%82%24%22%7C%22%E3%81%A7%E3%81%99%E3%80%82%24%22%7C%22%E3%81%BE%E3%81%99%E3%80%82%24%22%7C%22%E3%81%BE%E3%81%9B%E3%82%93%E3%80%82%24%22%7C%22%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82%24%22%7C%22%E3%81%BE%E3%81%9B%E3%82%93%E3%81%A7%E3%81%97%E3%81%9F%E3%80%82%22&from=jpn&to=und&orphans=no&unapproved=no&user=tommy_san&tags=&has_audio=yes&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=modified

**Comment by RyckRichards** [comment] 2016-03-20 16:31
sacredceltic told me that he couldn't reproduce this bug. Closing it.

**Closed by RyckRichards** 2016-03-20 16:31 UTC
Labels: bug
