### ISSUE TITLE
Indexed translations still appear in the advanced search

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1901] opened 2019-06-05 11:43 UTC
I'm currently translating sentences with a given word, and I want to exclude the sentences that already have Italian translations (the url I'm using: https://tatoeba.org/ita/sentences/search?query=%22%3Dgolf%22&from=eng&to=und&orphans=no&unapproved=no&native=yes&user=&tags=&list=&has_audio=&trans_filter=exclude&trans_to=ita&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&page=2&sort=random). However, some of the translations I contributed (for example: https://tatoeba.org/ita/sentences/show/7959103) are already indexed, but they still appear within my query, even if I specified that I want to exclude anything with translations into Italian

**Comment by trang** [comment] 2019-06-11 03:44
I can't reproduce.

I searched for ["=Tom wears a golf jacket"](https://tatoeba.org/eng/sentences/search?query=%22%3DTom+wears+a+golf+jacket%22&from=eng&to=und&orphans=no&unapproved=no&native=yes&user=&tags=&list=&has_audio=&trans_filter=exclude&trans_to=ita&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=random) instead of just "=golf". And there's no result (as expected).

Note that if there was less than 15 minutes between the time you added the translation and the time you saw it in the advanced search results, it's likely that it was not indexed yet.

**Comment by Guybrush88** [comment] 2019-06-11 15:57
I'm reproducing it also here: https://tatoeba.org/ita/sentences/search?query=&from=eng&to=und&orphans=no&unapproved=no&user=ck&tags=&list=&has_audio=&trans_filter=exclude&trans_to=ita&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=modified

This sentence: https://tatoeba.org/ita/sentences/show/7973123 has been indexed already (it was added almost an hour ago): https://tatoeba.org/ita/sentences/search?query=%22%3DTom+era+a+malapena+vivo.%22&from=ita&to=und

**Comment by Guybrush88** [comment] 2019-06-11 17:45
I just noticed that there's a delay between the two events, but I'm not sure about the exact timings

**Comment by jiru** [comment] 2019-06-14 08:41
For some reason, lately it takes more time to refresh the index, so the delay is more like 30 or 45 minutes.

**Comment by jiru** [comment] 2019-07-26 03:44
@Guybrush88 As far as I understand, the only problem here is the delay between the creation of new sentences and the search results, right? If so, I will close this issue. I confirm that when you opened this issue, the delay was higher than usual, and that problem is now tracked by #1929.

**Comment by Guybrush88** [comment] 2019-07-27 16:34
> As far as I understand, the only problem here is the delay between the creation of new sentences and the search results, right?

I guess so, I think it's safe to close this ticket, then

**Closed** 2019-07-27 22:57 UTC
