### ISSUE TITLE
Counter does not work when audio=yes

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#759] opened 2015-08-31 22:22 UTC
Even after translating some sentences in English that were not  translated into Portuguese, the "counter" does not change:

Page: 21 - https://tatoeba.org/eng/sentences/show_all_in/eng/por/por/only-with-audio/page:21

1st Print: Sentences NOT translated ("Tom divorced Mary last year." (#3923768) and "Tom didn't tell Mary to do that."(3923771))

► Counter = **155418** [ http://prntscr.com/8b50gc ]

2nd Print: Sentences translated, page wasn't refreshed

►Counter = **155418** [ http://prntscr.com/8b524g ]

3rd Print: Sentences translated, page refresh, 1st attempt: 

► Counter = **155418** [ http://prntscr.com/8b53ha ]

4th Print: Sentences translated, page refreshed once more, 2nd attempt: 

► Counter = **155418** [ http://prntscr.com/8b54z7 ]

I reproduced the same bug on Google Chrome:

1st print - "New" sentences NOT translated (Counter = **155418**)

► http://prntscr.com/8b57p2

2nd print: "New sentences translated, page not refreshed (Counter = **155418**)

► http://prntscr.com/8b5b36

3rd Print: Page refreshed. 2 "new new" sentences appear. (Counter = **155418**)

► http://prntscr.com/8b5dh1

I waited about 10  minutes to refresh the page again

4th print: Page refreshed again (Counter = 155428)

►http://prntscr.com/8b5krk

However, **when audio = no**, the "Counter" is updated

1st Print: Sentences NOT translated (Counter = **480915**)

Sentences I translated

I don't think Tom is as stupid as he used to be. (CK - #4483287)

Some people say Tom is stupid, but I think he's pretty smart. (CK - #4482386)

http://prntscr.com/8b5mlz

2nd Print: Sentences translated, page NOT refreshed (Counter = 480915)

http://prntscr.com/8b5nd4

3rd Print: Page refreshed (Counter = 480913)

http://prntscr.com/8b5otq

**Comment by trang** [comment] 2015-08-31 22:28
This is a duplicate of #718. It was fixed during the last Tatoeba Day.

**Closed** 2015-09-04 12:31 UTC
Labels: bug, duplicate
