### ISSUE TITLE
Is there a way for me to improve reduce the load of my queries? 

### ISSUE THREAD

**Issue by yotama9** [Tatoeba/tatoeba2#3063] opened 2023-05-28 19:50 UTC
Hi, 

I'm developing a webpage to help language learner (currently only the two of us) to track the words they've searched. The idea is to not give an immediate answer but rather to challenge the brain etc. 

I want to add tatoeba to the interface, but at the moment the call is relatively slow (about 10s on my home machine). Additionally, I'm getting 10 sentences, and for my purposes, getting 1 at time would actually be better. 

Is there a way for me to simplify the result? Basically, get the sentence id (so I can link to it) and the sentence in the original and target language? 

...
Of course, I understand that the DB queries cannot be tailored to my needs, so I'm only asking if there is something that is already available but I didn't find. 

Thank you.

**Comment by jiru** [comment] 2023-05-29 14:47
Can you give us a specific query that takes 10s to complete?

**Comment by jiru** [comment] 2023-05-29 14:48
As for the number of sentences returned, this issue is already tracked in #2983.

**Comment by ckjpn** [comment] 2023-05-31 00:20
Perhaps for your purposes, downloading the weekly export of our sentences and creating your own local search might work better for you.

Here's an old example that I created a few years ago.

http://goo.gl/6YLn1i

**Comment by ckjpn** [comment] 2023-05-31 19:16
@jiru

Some searches do take a long time.  Here's one example, just copy-and-pasted from my profile page.

🥝 See a random selection of my sentences that have audio by me and at least one directly-linked sentence.
https://tatoeba.org/en/sentences/search?list=4000&sort=random&trans_filter=limit&trans_link=direct&user=CK
There are over half a million of these. Be patient, since this kind of search may take 30 seconds or more.

There are times that even simpler queries take a long time.  I assume that perhaps it depends on how many others are making queries at the same time.

**Comment by yotama9** [comment] 2023-05-31 19:42
Thanks. 

I guessed this is the case. At the moment, this is the solution that I have. 

BTW, I'm looking at the output I get from tatoeba, and I see that I get all the translation that the sentence has, not only the one that I picked. Are there plans to narrow that down? It's probably a low priority at the moment, but I guess I can do part of the work there.

**Comment by ckjpn** [comment] 2023-05-31 19:55
You can narrow down which translations get shown by designating languages in your settings.
https://tatoeba.org/en/user/settings

This likely won't work for your website, though.

**Comment by yotama9** [comment] 2023-05-31 20:24
Thanks!

I actually see now that it is my fault. I've used the wrong language code in my API url.

**Comment by jiru** [comment] 2023-06-01 15:12
@yotama9 Alright :slightly_smiling_face: Shall I close this issue if the problem is solved for you?

**Comment by yotama9** [comment] 2023-06-01 18:33
@jiru Yes, please. Thank you so much for your help.

**Closed** 2023-06-02 05:22 UTC
Labels: enhancement
