### ISSUE TITLE
Can't delete items on the "Add vocabulary items" page.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1386] opened 2016-12-29 16:01 UTC
## The Problem
Clicking the trash icon on this page doesn't delete the item.

https://tatoeba.org/eng/vocabulary/add
![1](https://cloud.githubusercontent.com/assets/7934273/21547778/8598017c-ce2b-11e6-995e-1d69c325b198.png)

## However, it does work on this page.

https://tatoeba.org/eng/vocabulary/of/CK
![2](https://cloud.githubusercontent.com/assets/7934273/21547781/8adeb5f4-ce2b-11e6-8594-7bab5794d7fb.png)

**Comment by halfdan** [comment] 2016-12-29 16:09
Duplicate of #1377

**Comment by halfdan** [comment] 2016-12-29 16:10
This time I can however replicate the issue.

**Comment by halfdan** [comment] 2016-12-29 16:11
I believe this is fixed in dev - can you try to reproduce this on http://dev.tatoeba.org/?

**Comment by ckjpn** [comment] 2016-12-29 16:15
Works OK on dev.

**Closed** 2016-12-30 05:44 UTC
