### ISSUE TITLE
When clicking the edit sentence icon (the pencil), the text was doubled.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1522] opened 2017-12-09 03:46 UTC
https://tatoeba.org/eng/sentences/show/5254846

##Before Clicking

![screen shot 2017-12-09 at 12 40 50](https://user-images.githubusercontent.com/7934273/33792276-7c67a84c-dcde-11e7-9e7c-8dce584ebc56.png)

##After Clicking

![screen shot 2017-12-09 at 12 40 57](https://user-images.githubusercontent.com/7934273/33792282-8305b202-dcde-11e7-8653-3061ba80f11e.png)

##Possible Reason

Maybe this only happens when the sentence is 100% hiragana.

Here are some sentences by the same member that all need the 。added.
You can see that most of these don't have the same problem.

https://tatoeba.org/eng/activities/translate_sentences_of/daichan

**Comment by trang** [comment] 2017-12-10 18:12
Duplicate of #1427

**Closed by trang** 2017-12-10 18:12 UTC
