### ISSUE TITLE
When adding to lists, the pull-down menu and OK button look wrong on a Macintosh, using Chrome.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#722] opened 2015-07-18 23:51 UTC
This started happening a while back -- maybe 3 to 6 months ago -- I think a change was made to limit width of the SELECT.

I just assumed it looked this way on everybody's computer and thought maybe it was a decision that someone made. 

However, recently TRANG posted an image that shows it looks good on her computer.

Note that on a Macintosh running Firefox, the layout looks like TRANG's computer.
I didn't check in Safari and Opera.

Attached: 3 images.

1. Trang's computer
![2](https://cloud.githubusercontent.com/assets/7934273/8763982/532ee8b0-2df3-11e5-80d3-9e9677002d14.png)

2. CK's computer  (Macintosh using Chome)
![screen shot 2015-07-19 at 08 47 02](https://cloud.githubusercontent.com/assets/7934273/8763985/5ea9c4b2-2df3-11e5-8907-dd483ec1c483.png)

3. CK's computer with the option selected.
This also looks much different than Trang's screenshot.

![screen shot 2015-07-19 at 08 55 55](https://cloud.githubusercontent.com/assets/7934273/8763995/3c6d36b2-2df4-11e5-88cd-d41f438bd042.png)

**Comment by RyckRichards** [comment] 2016-03-20 18:03
According to Paul, he couldn't reproduce that bug. Closing this.

**Closed by RyckRichards** 2016-03-20 18:03 UTC
Labels: bug
