### ISSUE TITLE
"List of all members"/"Search user" only brings up exact match

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#3146] opened 2024-11-19 16:24 UTC
I was searching for a user with the username "samir_t", but I only remembered the "samir" part. Typing "samir" into the "Community"/"List of all members"/"Search user" field only brought up the user "samir". Likewise, typing "sam" into the field only brought up the user "sam".

It would be better if I could see all the users whose name started with a given substring (or perhaps simply contained a given substring, not necessarily at the beginning). I can imagine various ways to do this:

- as a given prefix string or substring is typed, dynamically show all the usernames that start with or contain it
- once "Enter" or the "Search" button is pressed, show a list of all the usernames that start with (or contain) the given substring and allow the user to select the desired one (for instance, by clicking on it)

**Comment by jiru** [comment] 2024-11-24 10:43
Yes, closing as a duplicate of #1994.

**Closed by jiru** 2024-11-24 10:43 UTC
Labels: enhancement
