### ISSUE TITLE
Overlapping of icons with "copy to clipboard" and "unapproved" options

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#922] opened 2015-11-11 22:29 UTC
I activated the new option of copying a sentence to the clipboard because I find it very useful when contributing with a smartphone, and I noticed that its icon is overlapping with the icon of unapproved sentences. I made a screenshot for this: http://i.imgur.com/ir5AtOB.png

**Comment by RyckRichards** [comment] 2016-03-20 13:48
Since this bug can't be reproduced anymore, I'm going to close this issue.

**Closed by RyckRichards** 2016-03-20 13:48 UTC
Labels: bug
