### ISSUE TITLE
Clean up empty sentences in the database before exporting

### ISSUE THREAD

**Issue by loolmeh** [Tatoeba/tatoeba2#303] opened 2014-06-08 09:57 UTC
Sentences like http://tatoeba.org/eng/sentences/show/3220389 shouldn't be allowed to be added in the first place. It can potentially break scripts working with our data.

**Comment by trang** [comment] 2016-05-01 14:56
I'm not sure how http://tatoeba.org/eng/sentences/show/3220389 happened but I'm unable to reproduce it. Even when removing the [UI validation](https://github.com/Tatoeba/tatoeba2/blob/dev/app/webroot/js/sentences.contribute.js#L40) and trying to add empty sentences or sentences with only spaces, it doesn't get added.

If one empty sentences make their way again into the database and we have a precise scenario, we can discuss how to proceed. Meanwhile I'm closing this.

**Closed by trang** 2016-05-01 14:56 UTC
Labels: bug
