### ISSUE TITLE
Display important buttons on latest sentences page

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#807] opened 2015-10-08 08:42 UTC
It'll be interesting once we'd save a lot of time and also contribute easily.

![idea 1](https://cloud.githubusercontent.com/assets/7658430/10361566/49f1f910-6d7f-11e5-80e2-cd92ef7bd4b6.PNG)

**Comment by trang** [comment] 2016-03-17 19:40
I'm planning to close this issue because the problem is not very clear. It doesn't seem to me that there would be any significant improvement if we added these buttons on the users "latest activity" page.

To translate the latest sentences of a user, there is already the "Translate {user}'s sentences" page, that can be accessed from the user's profile in the side bar. 
For instance: https://tatoeba.org/eng/activities/translate_sentences_of/Ricardo14

**Comment by RyckRichards** [comment] 2016-03-18 18:09
I thought that as far as we already are in someone's sentence page, we could add those sentences to a specific list we want or mark as "OK", "unsure" or "not OK", favorite it easily. It wouldn't be necessary to click on each sentence in order to do this.

**Comment by trang** [comment] 2016-03-18 23:59
Would this describe your problem:

**Problem**
I often check the latest sentences of some users in order to mark their sentences as "OK", "unsure" or "not OK" with the sentence ratings feature.
Currently it is not very practical for me to do this. I have to go to the profile of the user, then I click on "Show latest activity". That page that displays the latest sentences from the user. From there I have to click on each sentence, then wait for the sentence's page to load, then I can rate the sentence.
It would be more practical if I could access these buttons directly from the page that displays the latest activity of the user.

**Comment by RyckRichards** [comment] 2016-03-19 03:12
Yes, it definitely describes. Thank you!

**Comment by trang** [comment] 2018-06-25 01:03
Since the rating feature is still not out of "experimental phase", I'll close this. 

Basically this issue is about having a better way to proofread/rate sentences. I don't think adding the buttons in the "Latest activity" page would be the best thing to do. That page is meant to give an overview about what/when the user has contributed last.

@RyckRichards Technically if you want to proofread and rate the sentences of a certain user, you can use the "Translate sentences of XXX" page. The sentences there are ordered by latest created and have all the buttons.

**Closed by trang** 2018-06-25 01:03 UTC
Labels: enhancement, status:rejected
