### ISSUE TITLE
When displaying linked translations, move sentences in the same language to the top.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#773] opened 2015-09-18 22:05 UTC
It might be useful to show any sentence in the same language that is linked, just under the main sentence.  This way the languages are grouped together.

![screen shot 2015-09-19 at 06 58 12](https://cloud.githubusercontent.com/assets/7934273/9972183/fd505908-5e9c-11e5-8b96-0366e38e36fc.png)

**Comment by PaulPeer** [comment] 2015-09-19 09:08
I couldn't agree more!

**Comment by ckjpn** [comment] 2015-11-25 00:12
If this isn't too hard to do, I think it might be good to move this to the top of the list of things to do even though it isn't absolutely necessary.

Here's another example.

![screen shot 2015-11-25 at 09 07 26](https://cloud.githubusercontent.com/assets/7934273/11384619/8e99cfb6-9354-11e5-9eb9-99528c6d96eb.png)

**Comment by danail-georgiev** [comment] 2020-01-21 22:57
I investigated this issue and I came to the conclusion that the problem stems from SentencesTable findFilteredTranslations method. This two rows below 

               $directTranslations = Hash::sort($directTranslations, '{n}.lang', 'asc');
                $indirectTranslations = Hash::sort($indirectTranslations, '{n}.lang', 'asc');

are sorting the translations but to be honest I don't quire understands what is going wrong. 

So I have two questions:
- Do you think that this is the problematic area?
- And can someone propose a fix because I am not quite sure how to approach the situation.

**Comment by AndiPersti** [comment] 2020-01-22 03:57
As I understand it, CK wants that if a sentence has a direct translation in the same language, e.g. an English sentence has a direct translation in English, than this direct translation should be first. So after sorting `$directTranslations` you would need to move all direct English translations to the beginning of that array.

**Comment by Yorwba** [comment] 2020-01-22 11:11
There's some overlap here with issue #1907, which is also about the ordering of languages, except for indirect translations.

I guess we can all agree that sorting languages alphabetically isn't particularly helpful. Instead, we should put those languages first that a user is most likely to be interested in. However, I'm not sure whether translations in the same language are the most interesting ones. Logged-in users probably mostly want to see sentences in their profile languages. For logged-out users, we could use the system language of their browser to guess what they might be interested in.

**Comment by agrodet** [comment] 2020-01-27 16:21
Well, I have several remarks. As an initial note, there is only debating in my mind. Please excuse my long post.

First of all, that would be beneficial (and very nice) if when somebody considers working on an issue that impacts the website experience, the issue is actually discussed. That would avoid developing for personal needs. That would avoid sentences like "CK wants ...". I don't think we develop for the author of an issue, or even for people on Github.  
So what are the needs? What problem does the suggestion is supposed to solve? Is it from personal experience? Did we receive complaints or suggestions from others? Explain the needs, discuss the opinions. That's how we should design.

Some say "it might be useful", others say "we can all agree". Can we, though? As recent experience is showing, voices of the community can be gathered on the wall. Voices unheard here, on Github. Consensus may be reached, agreement much less likely. Discussion can avoid wasting time in development and handling upset users after the surprise design appears, just as another recent experience showed. That being said, let me turn to the topic of this issue.

CK says "this way the languages are grouped together".  
Well, they are already grouped together. Languages of translations are. Why a language of a translation should be group with a language of a sentence? Then, what do you do of languages of translations of translations?  
Besides, same language links are not translations, as demonstrated in #770. The fact that they are displayed as such is a design flaw. There is no need to correct a flaw by another.

Another issue. Doing what is suggested can bring parasites to the translator's mind. I know that some people don't do translation so let me explain. We translate the main sentence. Seeing a synonym can be misleading. It is even written in the rules of Tatoeba to not be influenced by other translations. Oh, that's okay with the "that's" "that is" bunch, but certainly not okay for sentences of similar meaning.

Yorwba says "I think we can all agree that sorting languages alphabetically isn't really helpful."  
Well, since I disagree, I guess we cannot all agree :). Why do I disagree? Very personal. I don't use Tatoeba for learning my second language. I used it because it's fun and I like languages. It happens that I translate eng to fra and link jpn to both. So when I go through the translations of English sentences, on my way down to fra, I will meet deu that will remind me of junior highschool. I will meet epo that will make me think that I really want to learn it and that I don't take the time to do it usually, so this time I can take some time to try to decipher it and see if I can make sense out of the translation. That my personal experience with Tatoeba. I admit that the alphabetical order fits me unexpectedly well and my personal experience is more to blame the design choice, but hey. Sorting by level of language wouldn't help because even if I were to register epo and deu in my profile, they will be below fra and jpn, and I will not encounter them.  
Now, one can say "yeah but that's your personal view" but if only personal argument is given on the other side, I'm good :P More seriously, if design is based on personal opinion, as soon as the change is implemented, I could come and ask to reverse it or make it fit my personal view. Since the first time worked like this, no reason for the second time not to work like this.

Finally, on a more general note, I think the "enhancement" tag is misleading. I feel like it is used for anything that is "function oriented". Its green color doesn't help as it implies that the issue received an okay to go. I think that some issues tagged "enhancement" are bad design ideas. I think a "need discussion" tag should exist. @trang @jiru 

Again, my apologies for the long post, and for mixing different topics to the discussion.

**Comment by trang** [comment] 2020-01-27 19:16
Well, @agrodet convinced me it's not worth spending more time on this issue, so I'm closing this. I'll create a new issue for the inconsistent "Translations" label for same-language linked sentences.

@danail-georgiev 
Sorry that you started to look into it, for pretty much nothing in the end. At least I hope the code exploration and @agrodet's zealous comment were somewhat educational.

@agrodet 
Whenever you see bad design ideas, just post a comment. That's enough to signal that there needs to be a discussion. I'm not sure what a label could offer more on top of that. Also we have the `unclear` label that conveys the idea that something needs to be clarified, which often implies a discussion. I think this label is enough for our current needs.

As for "enhancement", it actually is used for anything that is "function oriented". Unless I misunderstand what you mean by "function oriented". Any issue that implies changing how Tatoeba works (or is supposed to work) will be marked as "enhancement". Whether the problem that drives these changes is properly described or not is another matter. I have come to accept that it is difficult for the majority of users to submit an issue in the form of a problem to be solved and much easier to express their problems in the form of a solution to be implemented. So I personally label "enhancement" any issue where I can sense that there could be a valid problem to solve, even if the problem itself is not described at all. Then whenever I have enough motivation, I try to clarify things.

**Closed by trang** 2020-01-27 19:16 UTC
Labels: enhancement, good first issue
