### ISSUE TITLE
Search doesn't find old sentences owned by me

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1442] opened 2017-02-24 00:06 UTC
Reported by OsoHombre on the Wall:
https://tatoeba.org/eng/wall/show_message/28216#message_28216
also - https://tatoeba.org/eng/wall/show_message/28213#message_28213

1 - Browse for sentences that you posted - https://tatoeba.org/eng/sentences/of_user/Ricardo14/ yesterday or before - Example: https://tatoeba.org/eng/sentences/show/5874864 (Que horas você tem de ir dormir?)

2- The search engine displays "No results found for: Que horas você tem de ir dormir?" even it had been uploaded 

attempt 1 - any language - any language

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/23284522/c619b1f4-fa0a-11e6-9b2c-1963a5ea1f50.png)

attempt 2 - portuguese - any language:

![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/23284553/e5f1b652-fa0a-11e6-93e6-f6c123163360.png)

attempt 3 - portuguese - english

![screenshot_3](https://cloud.githubusercontent.com/assets/7658430/23284593/09e9a876-fa0b-11e6-9781-bd6175b7b794.png)

the sentence itself:

![screenshot_4](https://cloud.githubusercontent.com/assets/7658430/23284607/230a8a64-fa0b-11e6-920d-51b00554fe1f.png)

However, the sentence I posted a bit earlier - https://tatoeba.org/eng/sentences/show/5895787 - were found by the search engine:

![screenshot_5](https://cloud.githubusercontent.com/assets/7658430/23284724/ce05463e-fa0b-11e6-88a6-63cef4ec4b22.png)

**Comment by trang** [comment] 2017-02-24 01:05
In your case @RyckRichards, the problem is the same as the one mentioned in #1008, except this is with a question mark rather than exclamation mark.

If you remove the question mark from your search, you will find it your sentence:
https://tatoeba.org/eng/sentences/search?query=Que+horas+voc%C3%AA+tem+de+ir+dormir&from=und&to=und

I created another issue with more accurate information:  #1443. Closing this one.

**Closed** 2017-02-24 01:05 UTC
