### ISSUE TITLE
It's not possible to set up the language while posting on lists

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1544] opened 2018-04-10 14:24 UTC
Steps to reproduce?

1 - Pick any list like https://tatoeba.org/eng/sentences_lists/show/7703
2 - Post a sentence
3 - The new sentence's icon appears as "?" - http://prntscr.com/j3d6tzsince there's no way to set up the language as we do on "Add sentences" page - https://tatoeba.org/eng/sentences/add .

**Comment by trang** [comment] 2018-05-23 08:58
Note: this happens only when the option "Display sentences with the new design" is enabled.

**Comment by RyckRichards** [comment] 2018-05-23 09:38
but I didn't "active" that

**Comment by trang** [comment] 2018-07-08 17:10
Possibly fixed with #1474. I cannot reproduce at all on dev.

**Comment by RyckRichards** [comment] 2018-07-08 17:18
The sentence is showed up but the buttons above don't work.

**Comment by trang** [comment] 2018-07-08 17:19
@RyckRichards Are you testing on the dev website? I haven't updated yet the prod website so it won't work there.

**Comment by RyckRichards** [comment] 2018-07-08 17:20
No, I'm testing the prod.
https://youtu.be/RRgAPId_fag

**Comment by trang** [comment] 2018-07-08 17:39
@RyckRichards The prod website is updated now. I'll let you close this issue if you can no longer reproduce it on prod.

Note that your issue is not about the buttons, but about changing the language after adding a sentence to a list.

**Closed** 2018-07-08 17:44 UTC
Labels: bug
