### ISSUE TITLE
Search results don't have the keyword highlighted in yellow when furigana has manually been added and also in some other cases, too.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1272] opened 2016-07-27 03:16 UTC
## Screenshot
URL: https://tatoeba.org/eng/sentences/search?query=%E3%81%AE&from=jpn&to=eng
![screen shot 2016-07-27 at 12 11 31](https://cloud.githubusercontent.com/assets/7934273/17162765/deed7066-53f3-11e6-978b-855fb56f633b.png)

## Note
This is only a minor cosmetic bug, but I thought you would like to know.

**Comment by ckjpn** [comment] 2016-07-27 03:24
Notice that sometimes even without the furigana, the yellow highlighting doesn't happen.

URL: https://tatoeba.org/eng/sentences/search?query=%22%E3%81%A0%E3%81%91%22&from=jpn&to=eng
![screen shot 2016-07-27 at 12 20 23](https://cloud.githubusercontent.com/assets/7934273/17162902/00cd4886-53f5-11e6-9e57-ae2ba49e2331.png)

**Comment by ckjpn** [comment] 2016-07-27 05:35
Perhaps another example will help you track down the problem.

URL: https://tatoeba.org/eng/sentences/search?query=%22%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9%22&from=jpn&to=eng&trans_filter=limit&trans_to=und&orphans=no

![screen shot 2016-07-27 at 14 34 31](https://cloud.githubusercontent.com/assets/7934273/17164918/5ee4bfb4-5407-11e6-9a4c-89db46c5997f.png)

**Comment by ckjpn** [comment] 2016-07-27 07:04
Here is another example.  Perhaps this, too, will help you track down the problem.

https://tatoeba.org/eng/sentences/search?query=%22%E3%83%AC%E3%82%B8%E3%83%83%E3%83%88%E3%82%AB%E3%83%BC%E3%83%89%22&from=jpn&to=eng&trans_filter=limit&trans_to=und&orphans=any

![screen shot 2016-07-27 at 16 03 11](https://cloud.githubusercontent.com/assets/7934273/17166738/bb0d2356-5413-11e6-93b0-5c0c823fb214.png)

**Comment by trang** [comment] 2016-07-28 10:47
Duplicate of #1087.

**Closed by trang** 2016-07-28 10:47 UTC
