### ISSUE TITLE
Support Markdown on Comments

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#787] opened 2015-09-27 17:52 UTC
It would be awesome if Tatoeba support Markdown. It would solve some problems such as #81 (have a "@username" to warn a user in comment) and we would be able to *italicize*, **bold** them as well - which would help to avoid more typo mistakes, for example. it would be good if the message system support markdown also.

**Comment by Ppjet6** [comment] 2015-09-28 01:08
On 2015/09/27, Ricardo wrote:
> It would be awesome if Tatoeba support Markdown. It would solve some problems such as #81 (have a "@username" to warn a user in comment) and we would be able to *italicize*, **bold** them as well - which would help to avoid more typo mistakes, for example.

The `@username` feature will have to be implemented separatly as
Markdown does not do notifications, it's just for formatting.

-- 
Maxime Buquet

**Comment by ckjpn** [comment] 2015-09-28 01:13
Thoughts on this.

This may causes problems for those who use the exported data.
I'm not sure about this.

For me personally, allowing <i></i> would likely be helpful, since almost all my use of the Tatoeba Corpus is with HTML-related projects.  To be correct in English, there are times when titles need to be in italics.  There may be uses for <b></b>, but you can do a lot of reading in English and never see this.  Italics is sometimes used for emphasis, too.

A non-HTML markdown would perhaps be safer, even though less intuitive for many.  However, if you used the same markdown as Wikipedia, perhaps it would be well known.

**Comment by trang** [comment] 2015-10-11 14:42
I'm closing this since this is somewhat a duplicate of #651.

**Closed by trang** 2015-10-11 14:42 UTC
Labels: status:pending
