### ISSUE TITLE
Internal error when opening the page for adopting sentences

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#2121] opened 2020-02-03 12:42 UTC
Currently, each time I want to open the page that contains the orphan sentences from the top menu (i.e. https://tatoeba.org/ita/activities/adopt_sentences/ita, according to the interface language), I get an internal error message, so I can't open the page

**Comment by alanfgh** [comment] 2020-02-03 13:44
I can reproduce this.

**Comment by jiru** [comment] 2020-02-03 13:45
It looks like the error only happens with the option "(native)" is turned on.

**Comment by jiru** [comment] 2020-02-03 14:02
In addition, it looks that it’s not possible to unadopt with the setting enabled.

**Comment by AndiPersti** [comment] 2020-02-03 20:16
I'm sorry for the inconvenience. I've just pushed a fix.

**Comment by Guybrush88** [comment] 2020-02-03 21:42
@AndiPersti no problem, and thanks for the very quick fix :D

**Comment by ckjpn** [comment] 2020-02-04 03:46
## This can also be done with the advanced search.

This mimics the current way, without hiding the translations.
https://tatoeba.org/eng/sentences/search?orphans=yes&from=eng&sort=created

You can adjust the sorting and other additional search functions, too, if you wanted to.

Sort: words
https://tatoeba.org/eng/sentences/search?orphans=yes&from=eng&sort=words

Sort: random
https://tatoeba.org/eng/sentences/search?orphans=yes&from=eng&sort=random

Other options would be ...

- limit showing only ones with certain translations
- don't show any translations

**Comment by jiru** [comment] 2020-02-04 07:49
I’ve pushed Andreas’ fix to tatoeba.org, so you guys may now use the native indicator again.

**Closed by jiru** 2020-02-04 07:49 UTC
Labels: bug
