### ISSUE TITLE
Horus, the duplicate-merging script, is missing duplicates.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#2459] opened 2020-07-18 09:24 UTC
** Examples of the Problem **

https://tatoeba.org/eng/sentences/show/6263096
https://tatoeba.org/eng/sentences/show/8918001

I don't like going to the school.
added by Ricardo14, 2 days ago
I don't like going to school.
edited by Ricardo14, 2 days ago

https://tatoeba.org/eng/sentences/show/12621
https://tatoeba.org/eng/sentences/show/8916148

Just a minute
added by CK, 3 days ago
Just a minute.
edited by marafon, 2 days ago

https://tatoeba.org/eng/sentences/show/2374755
https://tatoeba.org/eng/sentences/show/8905463

I knew I can count on you.
added by Amastan, 7 days ago
I knew I could count on you.
edited by Amastan, 2 days ago

** Note **

Horus has run since these changes were made.
https://tatoeba.org/eng/sentence_comments/of_user/Horus

Horus
3 hours ago

**Comment by jiru** [comment] 2020-07-18 10:46
@ckjpn As always thanks for keeping an eye on our little Horus :slightly_smiling_face: 

The logs show a recurrent error that I wasn’t able to reproduce when I manually ran Horus on sentences modified less than 30 days ago because it just worked fine and merged 49 sentences. The recurrent error, which only appeared when Horus tried to merge sentences, was:
```
Traceback (most recent call last):
  File "/var/horus/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/var/horus/dedup/management/commands/deduplicate.py", line 597, in handle
    self.suppress_error(self.deduplicate, main_sent, ids, post_cmnt, dry)
  File "/var/horus/dedup/management/commands/deduplicate.py", line 371, in suppress_error
    cls.file_log.info(json.dumps(entry))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Sentences: Sentences object> is not JSON serializable
```

I’m not sure if this problem is solved already or not, so I’m going to monitor the logs closely.

**Comment by AndiPersti** [comment] 2020-07-19 19:48
We get that error message whenever Horus breaks because there's a problem while logging the error. A Django model (here `Sentences`) isn't serializable by default using `json.dumps()` and this error hides the real problem.
https://github.com/Tatoeba/horus/pull/5 in combination with https://github.com/Tatoeba/dj-tatoeba2/pull/6 should show us the real error in the future.

Horus itself should be fixed since last Friday evening (2020-07-17 19:00:00) and it works without problems since that time. All the mentioned duplicates are merged too.

**Closed by AndiPersti** 2020-07-19 19:48 UTC
Labels: bug
