### ISSUE TITLE
"Number of sentences having tag" not updated on sentence deletion

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#989] opened 2016-01-23 07:02 UTC
I think I found a bug.

It says that the tag "3358972"  - http://prntscr.com/9to9s8 - but whenever I click on it, it's displayed blank page - http://prntscr.com/9toa36. I didn't find any other tag in this "situation" - https://tatoeba.org/eng/tags/vi.../direction:asc

**Comment by jiru** [comment] 2016-01-23 20:25
The tag “3358972” exists and has been applied to the sentence 3361247, which has been deleted, so it’s normal no sentences are displayed (one would probably expect a message that says no sentences have that tag though). Only the sentence count on the search page is incorrect. Something wrong happened while the sentence has been deleted and the sentence counter hasn’t been decremented. Since we don’t know how that happened, we can’t solve the problem for the moment. If anyone can reproduce the problem on dev.tatoeba.org, we may be able to solve it.

**Comment by RyckRichards** [comment] 2016-01-23 20:57
Here we go

http://dev.tatoeba.org/eng/tags/show_sentences_with_tag/5712

![screenshot_1](https://cloud.githubusercontent.com/assets/7658430/12532772/26cb2654-c203-11e5-94fd-95ec4ba78a30.png)


![screenshot_2](https://cloud.githubusercontent.com/assets/7658430/12532765/1572733a-c203-11e5-8741-cc2c612aced6.png)

**Comment by jiru** [comment] 2016-01-23 22:29
Sorry, when I said “If anyone can reproduce the problem on dev.tatoeba.org”, I didn’t mean to find the same thing on dev. Instead, I meant to execute a sequence of operations, like adding/removing sentences, adding/removing tags etc. that result into the inconsistent state of having a tag with an incorrect number of sentences. Put it another way: make it happen again with a new tag and tell me how you did.

**Comment by RyckRichards** [comment] 2016-01-24 23:41
I created the sentence http://dev.tatoeba.org/eng/sentences/show/3838002 and tagged as 9999555. 
- http://prntscr.com/9uepbx

2nd -  I clicked over the tag name and I was redirected to the page - http://prntscr.com/9ueq0k

3rd - I deleted the sentence without "untagging" it - http://prntscr.com/9ueq7k

4th - I browsed by tag "9999555" - However, it's displayed 0 sentences http://prntscr.com/9ueqhu

**Comment by jiru** [comment] 2016-01-25 08:36
@RyckRichards Thank you very much.

**Comment by RyckRichards** [comment] 2016-03-20 16:23
I didn't find any other tag which I could reproduce this bug...

**Comment by phtan** [comment] 2016-07-01 19:10
I haven't found a way to reproduce this bug. I've tried tagging with '9999555', too, as @RyckRichards had.

**Comment by trang** [comment] 2016-07-01 21:33
I cannot reproduce either. I'm closing this.

**Closed by trang** 2016-07-01 21:33 UTC
Labels: bug
