### ISSUE TITLE
advanced search for sentences w/tag finds sentences that used to have the tag

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#2078] opened 2020-01-19 02:12 UTC
![bad_advanced_search](https://user-images.githubusercontent.com/1213027/72673334-d8502f00-3a36-11ea-948a-e0f71ebeb1ba.png)

Performing an advanced search for English sentences owned by iT4LL with the tag "@change" pulls up some sentences whose language has been changed, or that have had the tag removed. As you can see in the screenshot, some sentences have been reassigned to Portuguese. Others, such as "Since when do you enjoy going to the fair?", have had their tag removed.

**Comment by trang** [comment] 2020-01-19 16:24
Duplicate of #1978.

**Closed by trang** 2020-01-19 16:24 UTC
