### ISSUE TITLE
Revert Corrections/Modifications of Sentences to the Pre-Crash Versions

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1504] opened 2017-09-11 01:35 UTC
There are still many sentences with errors that had corrections made to them that were lost in the crash of June 2017.

These should be reverted.  There are slightly over 6,200 such sentences.

I've compared the modification dates of the June 10th exported files with the most recent export and have created a file with all the sentences that have a newer modification date in the June 10th export.

Not all modifications were changes to the text of the sentences.  Some of these modifications were ownership changes.  (Members released sentences that were later adopted by other members.)

Attached is an updated file that I sent to team@... on August 10th with the subject line "6,353 Sentences with Newer Modification Dates in the June 10, 2017 Export."

[sentences_detailed_ONES_NEEDING_REVERTED 2017-09-11.zip](https://github.com/Tatoeba/tatoeba2/files/1291096/sentences_detailed_ONES_NEEDING_REVERTED.2017-09-11.zip)

I've also included the Python script I wrote to create this file, so you can double-check what I did if you want to.  (This was also included in the email message to team@....)

[fix-sentences_detailed - version 2.zip](https://github.com/Tatoeba/tatoeba2/files/1291099/fix-sentences_detailed.-.version.2.zip)

You can also use this script with next week's export if you don't have time to revert these sentences' data this week.

This doesn't solve the problem of previously deleted sentences that may still be in the database.
It should be easy to check which older sentences ID numbers are still in the database that aren't in the June 10th export.  One thing to be careful of is that fact that I think perhaps "suspended" members' sentences may not be included in the exports.

**Comment by trang** [comment] 2017-09-17 16:42
Duplicate of #1484

**Closed by trang** 2017-09-17 16:42 UTC
