### ISSUE TITLE
Sentence Counts on "home" page are higher than on the browsing pages.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1207] opened 2016-06-17 03:35 UTC
## Problem

Note that the sentence counts for languages on the "home" page are higher than on the "broswing" pages.

The following 2 screenshots are of these 3 URLs.
https://tatoeba.org/eng
https://tatoeba.org/eng/sentences/show_all_in/eng/none/none/indifferent
https://tatoeba.org/eng/sentences/show_all_in/epo/none/none/indifferent

![screen shot 2016-06-17 at 12 31 41](https://cloud.githubusercontent.com/assets/7934273/16139994/dca1ad9e-3487-11e6-956d-3041465dd16b.png)
![screen shot 2016-06-17 at 12 31 21](https://cloud.githubusercontent.com/assets/7934273/16139993/dc9bdc02-3487-11e6-8872-24a3f12f8bf2.png)

**Comment by Guybrush88** [comment] 2016-06-17 14:30
maybe a cron job could be a solution for this, imho

**Comment by ckjpn** [comment] 2016-06-17 14:36
Notice that the numbers are quite different (over 2,000) and that the one on the "home" page is higher.
My guess is that this is something that would be solved by running the cron job more often and that it is another problem.  I could be wrong, though.

**Comment by trang** [comment] 2016-06-18 14:09
It can be solved by a cron job, it depends whether it is important or not that the stats are completely accurate. As far as I'm concerned, I don't think it is important.

In our case, the difference is indeed caused by the deduplication script. Whenever sentences are delete by Horus, the stats are not updated.

Note that the stats on the homepage are also cached and have a 15 minutes delay.

Anyway there is an issue regarding setting up a cron job (#966) so I'm closing this issue.

**Closed by trang** 2016-06-18 14:09 UTC
