### ISSUE TITLE
Tatoeba slowing down computers

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1055] opened 2016-03-10 16:41 UTC
Reported by [Hybrid](https://tatoeba.org/eng/user/profile/Hybrid) on the [Wall](https://tatoeba.org/eng/wall/show_message/25790#message_25790)

> Tatoeba slowing down my computer?

> Maybe it's just a problem with my computer, but I've noticed that some parts of Tatoeba really slow down my computer now. The Wall is fine, but all the webpages that have lists of sentences, like the log or when I click "show more..." slow down my browser. Does anyone else have this problem or is it just my computer?

https://tatoeba.org/eng/wall/show_message/25792#message_25792

> It happens to me when I use Firefox on Windows. Chrome is a little bit faster.

https://tatoeba.org/eng/wall/show_message/25804#message_25804

> https://tatoeba.org/eng/contributions/latest
> https://tatoeba.org/eng/contrib...of_user/Hybrid

> If I try to scroll down, it's very slow and Firefox can even stop working for a while. This didn't happen before.

**Comment by ckjpn** [comment] 2016-03-10 16:44
Is it tatoeba.org slowing down his computer, or the fact that tatoeba.org is sometimes slow?

My guess is this that it's the latter, and that this is likely not really a bug.

**Comment by RyckRichards** [comment] 2016-03-10 22:25
By [Pfirsichbaeumchen](https://tatoeba.org/eng/user/profile/Pfirsichbaeumchen) on the [Wall](https://tatoeba.org/eng/wall/show_message/25805#message_25805)

> I have experienced the same problem, and I also use Firefox. Reducing the number of displayed sentences seems to help.

**Comment by ckjpn** [comment] 2016-03-11 01:44
The way Pfirsichbaeumchen describes the problem and her solution implies this isn't a bug and that this issue can likely be closed.

**Comment by trang** [comment] 2016-03-12 17:25
I'm closing this. It is not something we can do much about. Hybrid mentioned himself:

> Thank you everyone for your answers. I think that it must be something with my computer.

**Closed by trang** 2016-03-12 17:25 UTC

**Comment by billoliver** [comment] 2016-03-13 00:50
I'm just passing by to let you guys know that I was able to duplicate this on my computer. And yes, it is a bug!

This is happening when users open [this page](https://tatoeba.org/eng/activities/translate_sentences_of/bill).

I think the problem is that too many sentences are being loaded on the page.

**Comment by jiru** [comment] 2016-03-13 03:04
I set 100 sentences per page, yet I’m unable to reproduce the problem with your link.

**Comment by ckjpn** [comment] 2016-03-13 06:39
http://www.webpagetest.org/

Perhaps the results stay online for a while.
Test for https://tatoeba.org/eng/activities/translate_sentences_of/bill

Firefox Test
http://www.webpagetest.org/result/160313_XS_7QW/

Chrome Test
http://www.webpagetest.org/result/160313_RB_7P0/

**Comment by ckjpn** [comment] 2016-03-13 06:42
Google PageSpeed Insights for the same page.

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftatoeba.org%2Feng%2Factivities%2Ftranslate_sentences_of%2Fbill

Mobile Screenshot taken from the results page.

![screen shot 2016-03-13 at 15 41 33](https://cloud.githubusercontent.com/assets/7934273/13727365/2c727746-e932-11e5-9fa2-b0dae261cd99.png)

**Comment by billoliver** [comment] 2016-03-13 06:43
@ckjpn Actually, you need to access this page:

https://tatoeba.org/eng/activities/translate_sentences_of/CK

**Comment by jiru** [comment] 2016-03-13 14:31
@ckjpn Your are testing the time it takes to load the page. It has very little to do with the original problem, that is to say slowdowns while scrolling after the page is loaded.

**Comment by ckjpn** [comment] 2016-03-13 14:33
I was just eliminating possibilities.

**Comment by billoliver** [comment] 2016-03-13 21:15
Reported by [alexmarcelo](http://tatoeba.org/eng/user/profile/alexmarcelo) on the Wall:

> After the update, Tatoeba is so slow in my computer that I can't use it anymore. In Firefox, the interface looks OK, but I can barely scroll down and up. In Edge, the icons look weird and the buttons are not functional at all.

**Comment by ckjpn** [comment] 2016-03-14 01:12
Could this possibly be caused by a CSS change done during the last update?

Perhaps if might be a good idea to revert back to what was being used before the update, until this can be figured out.  Or, maybe use that blue announcement feature to suggest that visitors try using a browser other than Firefox.

**Comment by billoliver** [comment] 2016-03-14 01:23
> Could this possibly be caused by a CSS change done during the last update?
Probably, but I'm sure yet.

> Or, maybe use that blue announcement feature to suggest that visitors try using a browser other than Firefox.

This is just bad UX. We must never suggest this to a user.

**Comment by ckjpn** [comment] 2016-03-14 01:39
> This is just bad UX. 

I agree.  What I meant was that temporarily this could be used if it's too much trouble to revert to the pre-update version of any feature that had CSS changed, assuming it's a CSS problem.
