### ISSUE TITLE
It's not possible to "change rating" on the same page

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1567] opened 2018-06-09 17:48 UTC
Steps to reproduce

1 - Activate the feature to rate sentences and build your collection of sentences.
2- Rate a sentence (example https://tatoeba.org/eng/sentences/show/3903005)
3 - Change your rate.

In case you want to change rating, you have to refresh the page.

► https://youtu.be/V0lErFsIwZ0

**Comment by trang** [comment] 2018-06-10 16:28
Duplicate of #1543

**Closed by trang** 2018-06-10 16:28 UTC
