### ISSUE TITLE
Possibility to manually input lists' names in the advanced search

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1662] opened 2018-09-04 06:49 UTC
Currently, there are 909 public lists, and in the advanced search you can choose a list only from a dropdown menu. This can be a long thing to do, especially if a user wants to search a list from the bottom of the dropdown.

Personally, I would find it useful to have two possible ways: the possibility to copy and paste the name the list's name, and the possibility to start typing the list's name and then seeing an autocompletion with all the names containing what the user typed (as it currently is for tags).

This, in my opinion would greatly improve the advanced search when using lists.

**Comment by trang** [comment] 2018-09-05 09:37
Duplicate of #1521

**Closed by trang** 2018-09-05 09:37 UTC
