### ISSUE TITLE
advanced search for sentences with a tag also finds sentences where the tag has been removed

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1986] opened 2019-10-13 16:20 UTC
If you do this search (for English sentences by user Ergulis that have the tag "@change", in chronological order):

https://tatoeba.org/eng/sentences/search?query=&from=eng&to=und&orphans=no&unapproved=no&user=Ergulis&tags=%40change&list=&has_audio=&trans_filter=limit&trans_to=und&trans_link=&trans_user=&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=created&sort_reverse=yes

many of the results no longer have tags (though I know that they once did). Examples:

https://tatoeba.org/eng/sentences/show/7963649
https://tatoeba.org/eng/sentences/show/8078118

**Comment by trang** [comment] 2019-10-13 16:52
Duplicate of #1978.

**Closed by trang** 2019-10-13 16:52 UTC
