### ISSUE TITLE
Search by number of translations

### ISSUE THREAD

**Issue by CangarejoAsul** [Tatoeba/tatoeba2#3092] opened 2023-12-09 22:54 UTC
https://tatoeba.org/wall/show_message/40365

> Please consider to add "Number of Translations" (at least, at most) (link: direct, indirect) in the search criteria in Advanced Search.
> 
> Some advantages:
> 1. For people who intend to translate or to find sentences with most translations could be useful, these sentences could be sometimes among the most popular/universal or the most easy sentences.
> 2. For people who intend to translate or to find sentences with few translations could be useful, these sentences could be sometimes among the most "virgin" sentences, or the less noisy sentences, etc.
> 3. Combining this criterion with some already present criteria could be very useful for the user to localize good sentences.
>
> For the "Length" of a sentences, the advanced search has already this useful feature: Length (At least, At most).
>
> "Number of translations" is not less important than some other criteria.
> Let compare it with two already criteria "orphan" and "unapproved" sentences.
> The below statistics (for top 20 languages on Tatoeba) shows that for most languages, orphan sentences and unapproved sentences are not a big deal.
> I am not saying orphan/unapproved criteria it is not useful, but my only point is that when we have these criteria for filtering just handful of sentences among tens of thousands of sentences, let have "Number of Translations'' as well.

**Comment by ckjpn** [comment] 2023-12-10 00:39
duplicate of https://github.com/Tatoeba/tatoeba2/issues/3090

**Closed** 2023-12-10 05:53 UTC
Labels: enhancement
