### ISSUE TITLE
When adding a tag fails, it looks like it has been added

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#1577] opened 2018-06-18 21:17 UTC
Steps to reproduce:
1. Find a sentence that has a tag
2. Try to add the same tag

Result: the yellow tag icon gets added to the end of the list, showing a list with the same tag two times. After refreshing the page, one can see that the tag wasn’t actually added.
Expected: show some error, or at least do not append the tag icon to the end of the tag list.

**Comment by AndiPersti** [comment] 2019-08-17 16:54
Duplicate of #1070?

**Comment by trang** [comment] 2019-08-17 21:20
Yes, duplicate. And this bug no longer exists so I'm closing this issue.

**Closed by trang** 2019-08-17 21:20 UTC
Labels: bug, good first issue
