### ISSUE TITLE
Duplicates not merged by Horus

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1932] opened 2019-07-27 07:01 UTC
These duplicates have been in the database for a while.

7305143	eng	"What are you doing?" "I am repeating by myself."	jimkillock
7350148	eng	"What are you doing?" "I am repeating by myself."	jimkillock
7305158	eng	"What are you repeating?" "The task which the Master set us today."	jimkillock
7350144	eng	"What are you repeating?" "The task which the Master set us today."	jimkillock
6003009	eng	Dear friends!	\N
6586792	eng	Dear friends!	Eccles17
6117054	eng	True.	\N
7811776	eng	True.	Goatstein
5940463	eng	What is your surname, first name and patronymic?	\N
7591778	eng	What is your surname, first name and patronymic?	\N

**Comment by jiru** [comment] 2019-07-28 06:41
* 7305143/7350148 and 7305158/7350144 are not exact duplicates, they use different quotes (curly vs. straight). This is the excepted behaviour for now.
* The other pairs you mentioned are exact duplicates, they should be merged, it’s a bug. I suspect it has to do with the license of the sentence. Each pair has one sentence licensed as CC-BY and the other "for Tatoeba only" which is not normal.

**Comment by agrodet** [comment] 2020-02-07 09:39
So that's the discussion we had on https://tatoeba.org/eng/sentences/show/6586792 three days ago :) 
Since Horus detected them on a full scan, do you still think it's license-related or that it was caused by another issue (ddos, crash, other)?

**Comment by ckjpn** [comment] 2020-03-06 05:02
Perhaps this is related.

This shows that Horus commented 3 hours ago.  It's now 2020-03-06   05:02. UTC.

https://tatoeba.org/eng/sentence_comments/of_user/Horus

<img width="559" alt="Screen Shot 2020-03-06 at 14 01 15" src="https://user-images.githubusercontent.com/7934273/76054143-ff48cd00-5fb2-11ea-8802-378052164535.png">

However, this duplicate was contributed over 15 hours ago.

<img width="568" alt="Screen Shot 2020-03-06 at 13 59 47" src="https://user-images.githubusercontent.com/7934273/76054110-e0e2d180-5fb2-11ea-96f9-92bbce9a05ae.png">

https://tatoeba.org/eng/sentences/show/8595346
...  duplicate of ...
https://tatoeba.org/eng/sentences/show/8595343

**Comment by jiru** [comment] 2020-03-06 05:49
@ckjpn These two sentences are different: one has a full stop while the other doesn't.

**Comment by ckjpn** [comment] 2020-03-06 06:29
I just realized that and came back to delete the message, but now that there is a comment, perhaps I should leave it.  Or, if you can, feel free to delete this and my other comment directly above.

**Comment by jiru** [comment] 2020-03-09 14:48
I’m going to close this issue since the mentioned sentences have been merged and AndiPersti recently fixed a bug that prevented duplicated from being merged. Feel free to open a new issue if you see any other exact duplicate.

**Closed by jiru** 2020-03-09 14:48 UTC
Labels: bug
