### ISSUE TITLE
Bug - Translate Sentences by USERNAME has the wrong error message when there are no sentences.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#694] opened 2015-06-26 03:37 UTC
https://tatoeba.org/eng/activities/translate_sentences_of/Swirlify
This user doesn't exist: Swirlify (0 results)

![screen shot 2015-06-26 at 12 33 06](https://cloud.githubusercontent.com/assets/7934273/8370250/14dd2554-1c00-11e5-9c54-86b7f142f5d5.png)

Also, notice that this error message is incorrect English.
https://tatoeba.org/eng/sentences/of_user/Swirlify
Swirlify does not have any sentence

It should be:

FROM:
Swirlify does not have any sentence
TO: (add the period, too)
Swirlify does not have any sentences.

**Comment by trang** [comment] 2015-06-26 12:12
Duplicate of #685.

**Closed by trang** 2015-06-26 12:12 UTC
