### ISSUE TITLE
blank space at the bottom of the UI language list

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#639] opened 2015-05-02 19:05 UTC
Here's a screenshot:

![whitespace](https://cloud.githubusercontent.com/assets/1213027/7442364/a4d5a478-f0dc-11e4-8f8d-eab392f66c33.png)

**Comment by trang** [comment] 2015-07-26 15:17
This is a problem that I was only able to notice on Firefox, on Windows.

The blank space is caused by the Marathi language (मराठी).

It seems like the height of the list is calculated based on the tallest element of the list (in this case, मराठी): `numElements x maxHeight`.
Since `मराठी` has a bigger height than the other elements, we end up with this extra space.

I'm not sure if there's anything we can do about this.

**Comment by jiru** [comment] 2015-07-26 23:11
I also noticed this problem using Firefox on Linux. It seemed more complex, more like caused by a particular combination of dropdown elements and fonts. However, @Ppjet6 reported that it was fixed on the latest Firefox nightly build, a few weeks ago. Anyone tried Firefox 39?

**Comment by alanfgh** [comment] 2015-07-27 02:33
I'm using Firefox 39 on Windows, and I see the problem.

**Comment by trang** [comment] 2015-07-30 20:43
I had tested it on Firefox 39 on Linux and didn't notice the problem. I also got to test it on Firefox 39 on Mac OS and there was no problem either.

It seems to be really something specific to Firefox on Windows, possibly related to the default font used. I didn't try to display Tatoeba with another font on Windows to see if the problem still occurs.

**Comment by trang** [comment] 2016-01-06 18:34
Currently on Firefox 43 on Windows, the blank space seems to have shrunk.

![languages_blank_space](https://cloud.githubusercontent.com/assets/221850/12150780/070bcf4e-b4ac-11e5-97a3-745c90f4675b.png)

Also, the problem doesn't occur on the dev website, where there are more languages.

![languages_blank_space_dev](https://cloud.githubusercontent.com/assets/221850/12150793/17f70332-b4ac-11e5-83e1-89b906ec1397.png)

**Comment by jiru** [comment] 2016-01-06 20:59
At the time of my previous comment, I remember the size of the space changed depending of the languages, their number and their order. It’s quite mysterious, but the space is still there and its size vary when we add new languages.

**Comment by jiru** [comment] 2016-03-12 18:19
With the latest addition of Ukrainian, the list now has a scrolling bar which seems to act as a workaround.

**Closed by jiru** 2016-03-12 18:19 UTC
Labels: bug
