### ISSUE TITLE
Japanese transcriptions/transliteration is not hidden when the sentence is 100% kana.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1017] opened 2016-02-24 10:32 UTC
I noticed it with this search.

https://tatoeba.org/jpn/sentences/search?query=&from=jpn&to=eng&orphans=yes&unapproved=no&user=&tags=&has_audio=&trans_filter=limit&trans_to=eng&trans_link=&trans_user=CK&trans_orphan=&trans_unapproved=&trans_has_audio=&sort=words

![screen shot 2016-02-24 at 19 30 22](https://cloud.githubusercontent.com/assets/7934273/13282624/39e735fa-db2d-11e5-8bd4-9d7542ad1722.png)

**Comment by jiru** [comment] 2016-02-29 02:58
It’s not a bug, it’s on purpose. Only furiganas that need review are hidden by default. Recently, I changed things so that furiganas of kana-only sentences are not marked as possibly wrong any more, because they obviously can’t be wrong.

Note that on the top of that, I’m working at displaying Japanese sentences with reviewed furigana on a single line (merging furigana and sentence), so these won’t look like strange duplications of the sentences. It’s already visible on dev.

**Closed by jiru** 2016-02-29 02:58 UTC
Labels: bug

**Comment by ckjpn** [comment] 2016-02-29 05:39
You've misunderstood.

100% hiragana items should not have furigana at all.

**Comment by trang** [comment] 2016-02-29 10:05
@ckjpn, gillux didn't misunderstand you. What he meant is that it's not a bug. The current behavior is normal, it just needs to be improved, and he's working on improving it. You can already see the improvement on the dev.

https://dev.tatoeba.org/eng/sentences/show/509772
https://dev.tatoeba.org/eng/sentences/show/3838034

**Comment by jiru** [comment] 2016-03-04 20:19
@ckjpn I agree that at first, one may think it doesn’t make much sense to have furigana attached on 100% kana sentences. However, I designed it that way because it’s easier to integrate with other transcriptions. It also makes the data more consistent, and thus easier to use for any tool making use of it. In the current implementation, the *lack* of furigana (no actual data stored, no furigana line displayed) has a different meaning. It means a technical problem prevented the furigana from being generated or edited. You may rarely see that because it mostly works, but it may happen.

**Comment by ckjpn** [comment] 2016-03-05 02:04
Perhaps you could do the following.

Generate the furigana as you are already doing it, but do a check before displaying it.
If the original and the furigana are the same, then don't display it.
