### ISSUE TITLE
Translating from a sentence often generates duplicates

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#1109] opened 2016-04-23 00:52 UTC
Reported by GrizaLeono, Wezel and soweli_Elepanto on the [Wall](https://tatoeba.org/eng/wall/show_message/26253#message_26253):

>Il arrive parfois que j'envoie une phrase, qui ensuite apparaît avec deux numéros consécutifs, par exemple les phrases #5075133 et #5075134.

> Cela arrive quand vous pressez le bouton « traduire » deux fois par mégarde. Une fois, j’en ai eu quatre, ces doubles. 

> I met such a problem too:
https://tatoeba.org/rus/sentences/show/5078678
https://tatoeba.org/rus/sentences/show/5078679
> It might be an bug in the software of the site.

**Comment by ventice** [comment] 2016-04-30 13:19
I've seen this myself several times during batch translations (100 sentences per session). Frequency of this bug appears to be 1 or 2 out of 100 translations. So, I guess it has some race condition issue behind it which means that the bug should be fixed more by elaborate analysis rather than by reproduction.
I'll try to do it.

**Comment by ventice** [comment] 2016-05-18 13:36
Looks like some echo from bug that `unbind()` on `app/webroot/js/sentences.add_translation.js:35`. When I commented it down, I got 6 instances of the sentence added. Looks like the second click sometimes occurs before unbind is run, which causes double request. I think unbinding isn't a stable solution - we have to hold registry of currently active requests and if second request arrives while another one is still active, discard it.

**Comment by ventice** [comment] 2016-05-18 15:35
Yes the reason was related to 'unbind()' but in a little different way. Actually, the original bug description provided a way to reproduce this bug with 100% guarantee:

> Cela arrive quand vous pressez le bouton «traduire» deux fois par mégarde. Une fois, j’en ai eu quatre, ces doubles.

Initially I thought that the author intended the button "Submit translation" with «traduire» but now I see that he/she meant the button that opens the translation controls - if you click the translate button while the controls are already open, you get second instances of event handlers bound to buttons and textarea so, when pressing the button you get two calls (that are execute both even though unbind is called in the first one). This can be worked around by the registry I mentioned, but it's easier to unbind event handlers immediately before binding them.

**Closed** 2016-05-19 21:30 UTC
Labels: bug
