### ISSUE TITLE
Adding long sentences using old design is difficult

### ISSUE THREAD

**Issue by jiru** [Tatoeba/tatoeba2#2230] opened 2020-03-25 14:01 UTC
Using the old design, I am going to the "Add sentence" page. From there, if I type in a sentence that is longer than the field width, the text never spans on multiple lines. Instead, it just scrolls left inside the field like this:
![image](https://user-images.githubusercontent.com/5107734/77544402-e95c6700-6ee3-11ea-9cab-84c90cac9b82.png)

Compare with the new design:
![image](https://user-images.githubusercontent.com/5107734/77544522-11e46100-6ee4-11ea-873d-716eff3b50d0.png)

**Comment by trang** [comment] 2020-03-25 16:34
Duplicate of #1462.

It's something I took into account in the new design but didn't backport into the old one.

**Closed by trang** 2020-03-25 16:34 UTC
Labels: bug
