### ISSUE TITLE
Add another column on https://tatoeba.org/eng/stats/sentences_by_language to include what people call their own language.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1877] opened 2019-04-28 01:52 UTC
## Suggested Enhancement

Add another column on https://tatoeba.org/eng/stats/sentences_by_language to include what people call their own language.

Similar to what's on http://www.manythings.org/sentences/audioplayer/ .

Perhaps, if it seems too crowded, you might consider removing the bar graph line, since it actually only seems to affect the top 16% of the languages.

**Comment by trang** [comment] 2019-08-26 15:37
Duplicate of #978.

**Closed by trang** 2019-08-26 15:37 UTC
Labels: enhancement, unclear
